// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using bbproto;

public class GachaWindowLogic : ConcreteComponent {
    
    public GachaWindowLogic(string uiName):base(uiName) {}
    
    public override void CreatUI () {
        //        LogHelper.Log("ScratchDecoratorUnity CreatUI Decddddddd1");
        base.CreatUI ();
        //        LogHelper.Log("ScratchDecoratorUnity CreatUI Decddddddd2");
    }
    
    public override void ShowUI () {
        //        LogHelper.Log("ScratchDecoratorUnity ShowUI Decddddddd1");
        base.ShowUI ();
        //        LogHelper.Log("ScratchDecoratorUnity ShowUI Decddddddd2");
    }
    
    public override void HideUI () {
        base.HideUI ();
    }
    
    public override void DestoryUI () {
        base.DestoryUI ();
    }
}