// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using bbproto;

public class GachaWindowLogic : ConcreteComponent {

    private UILabel titleLabel;
    private UILabel chanceLabel;

    public GachaWindowLogic(string uiName):base(uiName) {}

    public override void CreatUI () {
        base.CreatUI ();
        InitUI();
    }
    
    public override void ShowUI () {
        base.ShowUI ();
        MenuBtnsComponent.SetEnable(false);
    }
    
    public override void HideUI () {
        base.HideUI ();
        MenuBtnsComponent.SetEnable(true);
    }
    
    public override void DestoryUI () {
        base.DestoryUI ();
    }

    public virtual void InitUI(){

    }

}