//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: base.proto
namespace bbproto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Request")]
  public partial class Request : global::ProtoBuf.IExtensible
  {
    public Request() {}
    
    private int _version;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int version
    {
      get { return _version; }
      set { _version = value; }
    }
    private string _cli_ver = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cli_ver", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string cli_ver
    {
      get { return _cli_ver; }
      set { _cli_ver = value; }
    }
    private int _userid = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private string _username = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Response")]
  public partial class Response : global::ProtoBuf.IExtensible
  {
    public Response() {}
    
    private int _version;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int version
    {
      get { return _version; }
      set { _version = value; }
    }
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private string _data = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: quest.proto
// Note: requires additional types generated from: base.proto
namespace bbproto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Unit")]
  public partial class Unit : global::ProtoBuf.IExtensible
  {
    public Unit() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _skills1 = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"skills1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string skills1
    {
      get { return _skills1; }
      set { _skills1 = value; }
    }
    private string _skills2 = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"skills2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string skills2
    {
      get { return _skills2; }
      set { _skills2 = value; }
    }
    private string _profile = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"profile", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string profile
    {
      get { return _profile; }
      set { _profile = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UnitInfo")]
  public partial class UnitInfo : global::ProtoBuf.IExtensible
  {
    public UnitInfo() {}
    
    private int _uniqueId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uniqueId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int uniqueId
    {
      get { return _uniqueId; }
      set { _uniqueId = value; }
    }
    private int _id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _exp = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _addPow = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"addPow", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int addPow
    {
      get { return _addPow; }
      set { _addPow = value; }
    }
    private int _addDef = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"addDef", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int addDef
    {
      get { return _addDef; }
      set { _addDef = value; }
    }
    private int _addHp = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"addHp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int addHp
    {
      get { return _addHp; }
      set { _addHp = value; }
    }
    private int _limitbreakLv = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"limitbreakLv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int limitbreakLv
    {
      get { return _limitbreakLv; }
      set { _limitbreakLv = value; }
    }
    private int _getTime = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"getTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int getTime
    {
      get { return _getTime; }
      set { _getTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QuestInfo")]
  public partial class QuestInfo : global::ProtoBuf.IExtensible
  {
    public QuestInfo() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _state = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int state
    {
      get { return _state; }
      set { _state = value; }
    }
    private int _no = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"no", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int no
    {
      get { return _no; }
      set { _no = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _desc = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string desc
    {
      get { return _desc; }
      set { _desc = value; }
    }
    private int _stamina = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"stamina", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int stamina
    {
      get { return _stamina; }
      set { _stamina = value; }
    }
    private int _floor = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"floor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int floor
    {
      get { return _floor; }
      set { _floor = value; }
    }
    private int _rewardExp = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"rewardExp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rewardExp
    {
      get { return _rewardExp; }
      set { _rewardExp = value; }
    }
    private int _rewardCoin = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"rewardCoin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rewardCoin
    {
      get { return _rewardCoin; }
      set { _rewardCoin = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _all_unit_kind = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(10, Name=@"all_unit_kind", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> all_unit_kind
    {
      get { return _all_unit_kind; }
    }
  
    private bbproto.UnitInfo _boss = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"boss", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bbproto.UnitInfo boss
    {
      get { return _boss; }
      set { _boss = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QuestMapInfo")]
  public partial class QuestMapInfo : global::ProtoBuf.IExtensible
  {
    public QuestMapInfo() {}
    
    private int _version = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int version
    {
      get { return _version; }
      set { _version = value; }
    }
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private readonly global::System.Collections.Generic.List<bbproto.QuestInfo> _questlist = new global::System.Collections.Generic.List<bbproto.QuestInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"questlist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bbproto.QuestInfo> questlist
    {
      get { return _questlist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqGetQuestMap")]
  public partial class ReqGetQuestMap : global::ProtoBuf.IExtensible
  {
    public ReqGetQuestMap() {}
    
    private bbproto.Request _req = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"req", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bbproto.Request req
    {
      get { return _req; }
      set { _req = value; }
    }
    private int _start_id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"start_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int start_id
    {
      get { return _start_id; }
      set { _start_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspGetQuestMap")]
  public partial class RspGetQuestMap : global::ProtoBuf.IExtensible
  {
    public RspGetQuestMap() {}
    
    private bbproto.Response _resp = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"resp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bbproto.Response resp
    {
      get { return _resp; }
      set { _resp = value; }
    }
    private readonly global::System.Collections.Generic.List<bbproto.QuestMapInfo> _maps = new global::System.Collections.Generic.List<bbproto.QuestMapInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"maps", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bbproto.QuestMapInfo> maps
    {
      get { return _maps; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: person.proto
namespace msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Person")]
  public partial class Person : global::ProtoBuf.IExtensible
  {
    public Person() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _email = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"email", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string email
    {
      get { return _email; }
      set { _email = value; }
    }
    private readonly global::System.Collections.Generic.List<msg.Person.phone_number> _phone = new global::System.Collections.Generic.List<msg.Person.phone_number>();
    [global::ProtoBuf.ProtoMember(4, Name=@"phone", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<msg.Person.phone_number> phone
    {
      get { return _phone; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _test_packed = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(5, Name=@"test_packed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<int> test_packed
    {
      get { return _test_packed; }
    }
  
    private int _test_deprecated = default(int);
    [global::System.Obsolete, global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"test_deprecated", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int test_deprecated
    {
      get { return _test_deprecated; }
      set { _test_deprecated = value; }
    }
    private int _foreach = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"foreach", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int @foreach
    {
      get { return _foreach; }
      set { _foreach = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"phone_number")]
  public partial class phone_number : global::ProtoBuf.IExtensible
  {
    public phone_number() {}
    
    private string _number;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"number", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string number
    {
      get { return _number; }
      set { _number = value; }
    }
    private msg.Person.phone_type _type = msg.Person.phone_type.home;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(msg.Person.phone_type.home)]
    public msg.Person.phone_type type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"phone_type")]
    public enum phone_type
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"mobile", Value=0)]
      mobile = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"home", Value=1)]
      home = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"work", Value=2)]
      work = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"opaque_message_list")]
  public partial class opaque_message_list : global::ProtoBuf.IExtensible
  {
    public opaque_message_list() {}
    
    private readonly global::System.Collections.Generic.List<byte[]> _messages_list = new global::System.Collections.Generic.List<byte[]>();
    [global::ProtoBuf.ProtoMember(1, Name=@"messages_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<byte[]> messages_list
    {
      get { return _messages_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}