// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class MsgWindowLogic : ConcreteComponent
{
    public MsgWindowLogic(string uiName):base(uiName){}

    public override void ShowUI()
    {
        base.ShowUI();
        AddListener();
    }
    
    public override void HideUI()
    {
        base.HideUI();
        RemoveListener();
    }
    
    public override void DestoryUI()
    {
        base.DestoryUI();
    }
    
    void AddListener()
    {
        MsgCenter.Instance.AddListener(CommandEnum.OpenMsgWindow, OpenMsgWindow);
    }
    
    
    void RemoveListener()
    {
        MsgCenter.Instance.RemoveListener(CommandEnum.OpenMsgWindow, OpenMsgWindow);
    }
    
    public override void CallbackView(object data)
    {
        base.CallbackView(data);
        CallBackDispatcherArgs cbdArgs = data as CallBackDispatcherArgs;
        switch (cbdArgs.funcName)
        {
        case "ClickSure":
//            CallBackDispatcherHelper.DispatchCallBack(SendMessage, cbdArgs);
            break;
        default:
            break;
        }
    }
    

    void OpenMsgWindow(object msg){
//        Dictionary<string,string> noteMsg = msg as Dictionary<string,string>;
        CallBackDispatcherArgs cbdArgs = new CallBackDispatcherArgs("ShowMsg", msg);
        ExcuteCallback(cbdArgs);
    }
    
    
}

