// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;
using bbproto;


public class RestoreStamina: ProtoManager {
    // req && rsp
    private bbproto.ReqRestoreStamina reqRestoreStamina;
    private bbproto.RspRestoreStamina rspRestoreStamina;
    // state for req
    // data
    
    public RestoreStamina() {
    }
    
    ~RestoreStamina () {
    }
    
    public static void SendRequest(DataListener callBack) {
        RestoreStamina acceptFriend = new RestoreStamina();
        acceptFriend.OnRequest(null, callBack);
    }
    
    //Property: request server parameters
    //    public uint FriendUid { get { return friendUid; } set { friendUid = value; } }
    
    
    //make request packet==>TODO rename to request
    public override bool MakePacket() {
        Proto = Protocol.RESTORE_STAMINA;
        reqType = typeof(ReqRestoreStamina);
        rspType = typeof(RspRestoreStamina);
        
        reqRestoreStamina = new ReqRestoreStamina();
        reqRestoreStamina.header = new ProtoHeader();
        reqRestoreStamina.header.apiVer = Protocol.API_VERSION;
        reqRestoreStamina.header.userId = DataCenter.Instance.UserInfo.UserId;
        
        //request params
        ErrorMsg err = SerializeData(reqRestoreStamina); // save to Data for send out
        
        return (err.Code == (int)ErrorCode.SUCCESS);
    }
    
}

