// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using bbproto;



public class EvolveStart: ProtoManager {
    // req && rsp
    private bbproto.ReqEvolveStart reqEvolveStart;
    private bbproto.RspEvolveStart rspEvolveStart;

    public uint BaseUnitId { set { baseUnitId = value; } }
    public List<uint> PartUnitId { set { partUnitId = value; } }
    public uint HelperUserId { set { helperUserId = value; } }
        
    private uint baseUnitId;
    private List<uint> partUnitId;
    private uint helperUserId;
    private UserUnit helperUnit;
    private int helperPremium;
    private uint evolveQuestId;
    
    public EvolveStart() {
    }
    
    ~EvolveStart () {
    }
    
    //Property: request server parameters

    //make request packet==>TODO rename to request
    public override bool MakePacket() {
        Proto = Protocol.DEL_FRIEND;
        reqType = typeof(ReqEvolveStart);
        rspType = typeof(RspEvolveStart);
        
        reqEvolveStart = new ReqEvolveStart();
        reqEvolveStart.header = new ProtoHeader();
        reqEvolveStart.header.apiVer = Protocol.API_VERSION;
        reqEvolveStart.header.userId = DataCenter.Instance.UserInfo.UserId;
        
        //request params
//        reqEvolveStart.friendUid = friendUids;
        
        ErrorMsg err = SerializeData(reqEvolveStart); // save to Data for send out
        
        return (err.Code == (int)ErrorCode.SUCCESS);
    }
    
}

