// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

public interface ITestRunner {
    void run();
}

public class ModelTestManager {
    private Dictionary <string, ITestRunner> testDic = new  Dictionary<string, ITestRunner>();

    private ModelTestManager() {
        init();
    }

    private static ModelTestManager instance;
    public static ModelTestManager Instance {
        get {
            return instance;
        }
    }

    public void init() {

    }

    public void AddTester(string testName, ITestRunner runner) {
        if (testDic.ContainsKey(testName)) {
            return;
        } else {
            testDic.Add(testName, runner);
        }
    }

    public void RunAll() {
        foreach (KeyValuePair<string, ITestRunner> item in testDic) {
            item.Value.run();
        }
    }
}

