
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;
using bbproto;


public class UnitMaxExpand: ProtoManager {
    // req && rsp
    private bbproto.ReqUnitMaxExpand reqUnitMaxExpand;
    private bbproto.RspUnitMaxExpand rspUnitMaxExpand;
    // state for req
    // data
    
    public UnitMaxExpand() {
    }
    
    ~UnitMaxExpand () {
    }
    
    public static void SendRequest(DataListener callBack) {
        UnitMaxExpand acceptFriend = new UnitMaxExpand();
        acceptFriend.OnRequest(null, callBack);
    }
    
    //Property: request server parameters
    //    public uint FriendUid { get { return friendUid; } set { friendUid = value; } }
    
    
    //make request packet==>TODO rename to request
    public override bool MakePacket() {
        Proto = Protocol.UNIT_MAX_EXPAND;
        reqType = typeof(ReqUnitMaxExpand);
        rspType = typeof(RspUnitMaxExpand);
        
        reqUnitMaxExpand = new ReqUnitMaxExpand();
        reqUnitMaxExpand.header = new ProtoHeader();
        reqUnitMaxExpand.header.apiVer = Protocol.API_VERSION;
        reqUnitMaxExpand.header.userId = DataCenter.Instance.UserInfo.UserId;
        
        //request params
        ErrorMsg err = SerializeData(reqUnitMaxExpand); // save to Data for send out
        
        return (err.Code == (int)ErrorCode.SUCCESS);
    }
    
}

