// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class MsgWindowModule : ModuleBase{
	public MsgWindowModule(UIConfigItem config):base(  config){
		CreateUI<MsgWindowView> ();
	}

	public override void OnReceiveMessages (params object[] data)
	{
		base.OnReceiveMessages (data);
	}
}

