// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

public class CollectionHelper {
    public CollectionHelper() {

    }

    public static void ResetReadOnlyList<T>(List<T> orig, List<T> des) {
        orig.Clear();
        for (int i = 0; i < des.Count; i++) {
            orig.Add(des[i]);
        }
    }
}

