// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;

public enum ErrorCode {
    Succeed = 0,

    // usual
    IllegalParam = -1000,

    // network
    NetWork = -2000,
    TimeOut = -2001,

    // model
    Model = -3000,
    Encrypt = -3001,
    Decrypt = - 3002, 
    IllegalData = -3003,

    // controller
    Controller = -4000,

    // view
    View = -5000,
};

/// <summary>
/// Error message.
/// </summary>
public class ErrorMsg {

    /// <summary>
    /// The code.
    /// </summary>
    private ErrorCode code = ErrorCode.Succeed;
    public ErrorCode Code {
        get { return code; }
        set { code = value; }
    }

    /// <summary>
    /// The message.
    /// </summary>
    private string msg = "";
    public string Msg {
        get { return msg; }
        set { msg = value; }
    }


    public ErrorMsg(){
    }

    public ErrorMsg(ErrorCode errorCode, string message){
        code = errorCode;
        msg = message;
    }
}