// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
public partial class TextCenter {
    void InitSecond(){
        textDict.Add("BigRareWarning", "Rare Warning");
        textDict.Add("BigRareWarningText", "Include the unit whose rare bigger than 3.\nAre you sure to sell?");

		textDict.Add("FriendCounterTitle", "Friends :");
		textDict.Add("UnitCounterTitle", "Units :");


		textDict.Add("CounterCurrent",  "{0}");
		textDict.Add("CounterMax",  "/{0}");

    }
}

