// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
public partial class TextCenter {
    void InitSecond(){
        textDict.Add("BigRareWarning", "Rare Warning");
        textDict.Add("BigRareWarningText", "Include the unit whose rare bigger than 3.\nAre you sure to sell?");

		textDict.Add("UnitOverflow", "Unit Overflow");
		textDict.Add("UnitOverflowText", "Your current unit capacity is {0}/{1}.\nWould you like to do unit expansion?");

		textDict.Add("FirendOverflow", "Firend Overflow");
		textDict.Add("FriendOverflowText", "Your current unit capacity is {0}/{1}.\nWould you like to do friend expansion?");

		textDict.Add("CostLimit", "Current Cost Limit");
		textDict.Add("CostLimitText", "Sorry to tell you,\nyou can't replace this unit! ");

		textDict.Add("FriendCounterTitle", "Friends :");
		textDict.Add("ApplyCounterTitle", "Apply :");
		textDict.Add("ReceptionCounterTitle", "Recept :");
		textDict.Add("UnitCounterTitle", "Units :");


		textDict.Add("CounterCurrent",  "{0}");
		textDict.Add("CounterMax",  "/{0}");

		textDict.Add("StageStateNew", "New");
		textDict.Add("StageStateClear", "Clear");
		textDict.Add("StaminaLackNoteTitle", "Friendly Reminder");
		textDict.Add("StaminaLackNoteContent", "Current Stamina is not enough to battle!");

		textDict.Add("SelectRoleTitle", "Select Role");
		textDict.Add("SelectRoleContent", "Are you sure to select this role to adventure with you?");

		textDict.Add("DeleteNoteTitle", "Delete Friend");
		textDict.Add("DeleteNoteContent", "Are you sure to delete this friend?");

		textDict.Add("ZeroFriendPoint", "Don't get friend point.");
		textDict.Add("GotFriendPoint", "You have got {0} friend point.");


    }
}

