
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
public partial class TextCenter {
    private void InitThird(){

//		MsgWindowParams mwp = new MsgWindowParams ();
//		mwp.btnParams = new BtnParam[2];
//		mwp.titleText = "Retry";
//		mwp.contentText = "Use two stone to retry this floor of quest ?";
//		
//		BtnParam sure = new BtnParam ();
//		sure.callback = SureRetry;
//		sure.text = "OK";
//		mwp.btnParams[0] = sure;
//		
//		sure = new BtnParam ();
//		sure.callback = EnterNextFloor;
//		sure.text = "Cancel";
//		mwp.btnParams[1] = sure;
//
//		MsgCenter.Instance.Invoke(CommandEnum.OpenMsgWindow, mwp);

		//novice guide(new hand)
		textDict.Add ("guide1_title", "Welcom!");
		textDict.Add ("guide1_content", "Are you going to get into the saint gate?");
		textDict.Add ("guide2_title", "choose your partener");
		textDict.Add ("guide2_content", "选择和你一起冒险的伙伴。\n未选择的伙伴会在之后的旅程中相遇！");
		textDict.Add ("guide3_title", "determine your partener");
		textDict.Add ("guide3_content", "角色介绍。\n确定和xxx冒险么？");
		textDict.Add ("guide4_title", "start adventure");
		textDict.Add ("guide4_content", "我的名字叫xxx。\n那么就立马开始冒险吧！");
		textDict.Add ("guide5_title", "about scratch card");
		textDict.Add ("guide5_content", "接下来就是重中之重的抽卡！\n抽卡可是能得到各种各样的强卡哦！");
		textDict.Add ("guide6_title", "about rare card");
		textDict.Add ("guide6_content", "这次就来一次稀有抽卡吧。\n友情抽卡咱放后面再说。");
		textDict.Add ("guide7_title", "a rare card need something");
		textDict.Add ("guide7_content", "a rare card need something!");
		textDict.Add ("guide8_title", "choose a card");
		textDict.Add ("guide8_content", "任意选择一张卡牌吧。不管选哪一张，结果其实是一样的。");
		textDict.Add ("guide9_title", "get a card");
		textDict.Add ("guide9_content", "运气不错，卡牌很强！\n后别忘了编入队伍中哦。");
		textDict.Add ("guide10_title", "party method");
		textDict.Add ("guide10_content", "choose a party");
		textDict.Add ("guide11_title", "party complete");
		textDict.Add ("guide11_content", "complete a party");

		textDict.Add ("guide12_title", "start mission");
		textDict.Add ("guide12_content", "find the key to open the door");
		textDict.Add ("guide13_title", "move method");
		textDict.Add ("guide13_content", "click the direction to move");
		textDict.Add ("guide14_title", "gold box");
		textDict.Add ("guide14_content", "you get some gold.");
		textDict.Add ("guide15_title", "movement and sp");
		textDict.Add ("guide15_content", "every move costs one sp.so don't let the sp goto 0.");
		textDict.Add ("guide16_title", "enemy floor");
		textDict.Add ("guide16_content", "five star means dangerous.be careful to move.Then we'll be in battle!");
		textDict.Add ("guide17_title", "xxx teacher teach you lesson");
		textDict.Add ("guide17_content", "let me give you a lesson!");
		textDict.Add ("guide18_title", "xxx teacher do the work himself");
		textDict.Add ("guide18_content", "do you see my excellent work!");

		//attack once
		textDict.Add ("guide19_title", "attack method");
		textDict.Add ("guide19_content", "the same gird has 2 or more same color will attack.");
		textDict.Add ("guide20_title", "your turn");
		textDict.Add ("guide20_content", "try to put the blue color in one grid.");

		//attack twice
		textDict.Add ("guide21_title", "attack successed");
		textDict.Add ("guide21_content", "try to drag the same color with the left corner");
		textDict.Add ("guide22_title", "attack key point");
		textDict.Add ("guide22_content", "1.same color in one grid.\n 2.2 or more same color will attack.\n 3.one grid will take 5 color at most. then start fight!");
		textDict.Add ("guide23_title", "Conquer the enemy");
		textDict.Add ("guide23_content", "Congratulations! then take the key!");
		textDict.Add ("guide24_title", "key floor");
		textDict.Add ("guide24_content", "then you have the key, the door is open. Advance to there!");
		textDict.Add ("guide25_title", "arrive at the door");
		textDict.Add ("guide25_content", "boss is waiting.click the door to open it.");

		//boss attck
		textDict.Add ("guide26_title", "boss fight!");
		textDict.Add ("guide26_content", "slide the blocks to sort them");
		textDict.Add ("guide27_title", "enemy attack");
		textDict.Add ("guide27_content", "the enemy attack us. our hp going down. take the red heart block.");
		textDict.Add ("guide28_title", "red heart max");
		textDict.Add ("guide28_content", "put 2 red heart in one grid to increase hp.");
		textDict.Add ("guide29_title", "heal succeed!");
		textDict.Add ("guide29_content", "take down the boss");

		//skill
		textDict.Add ("guide30_title", "active skill");
		textDict.Add ("guide30_content", "the unit is flashing.click it.");
		textDict.Add ("guide31_title", "use active skill");
		textDict.Add ("guide31_content", "use the active skill");
		textDict.Add ("guide32_title", "nice action");
		textDict.Add ("guide32_content", "different charactor has different skill.");
		textDict.Add ("guide33_title", "about boost");
		textDict.Add ("guide33_content", "the boost will add 1.5 times hurt and heal.");
		textDict.Add ("guide34_title", "go through the copy successfully");
		textDict.Add ("guide34_content", "find the key.take down the boss.you will succeed.");
		textDict.Add ("guide35_title", "confirm the result");
		textDict.Add ("guide35_content", "confirm the result.you will gain different things.");

		//level up
		textDict.Add ("guide41_title", "level up method");
		textDict.Add ("guide41_content", "click level up to strong your party");
		textDict.Add ("guide42_title", "choose the level up card");
		textDict.Add ("guide42_content", "choose the card");
		textDict.Add ("guide43_title", "material card choose");
		textDict.Add ("guide43_content", "choose your material card");
		textDict.Add ("guide44_title", "choose your helper");
		textDict.Add ("guide44_content", "choose a friend");
		textDict.Add ("guide45_title", "friend reward");
		textDict.Add ("guide45_content", "the same attr results a lot of exp");
		textDict.Add ("guide46_title", "level up end");
		textDict.Add ("guide46_content", "level up max.now goto the evolve");

		//evolve
		textDict.Add ("guide51_title", "choose evolve card");
		textDict.Add ("guide51_content", "choose card");
		textDict.Add ("guide52_title", "choose a helper");
		textDict.Add ("guide52_content", "you need a helper.choose one");
		textDict.Add ("guide53_title", "choose a helper's need");
		textDict.Add ("guide53_content", "the helper shoulder have the same race,attr,lv.");
		textDict.Add ("guide54_title", "about the evolve mission");
		textDict.Add ("guide54_content", "you must finish the mission to complete evolve");
		textDict.Add ("guide55_title", "evovle mission final confirm");
		textDict.Add ("guide55_content", "use this team to fight.let's go");
		textDict.Add ("guide56_title", "xxx teacher's note");
		textDict.Add ("guide56_content", "take down more enemy");
		textDict.Add ("guide57_title", "mission key point");
		textDict.Add ("guide57_content", "1.find the key;2.goto the door");
		textDict.Add ("guide58_title", "evolve success");
		textDict.Add ("guide58_content", "excelent,your charactor evovles.");
		textDict.Add ("guide59_title", "evolve time");
		textDict.Add ("guide59_content", "1.find the key;2.goto the door");
//		textDict.Add ("guide8_title", "");
//		textDict.Add ("guide8_content", "");

    }
}

