// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections;
using UnityEngine;

/// </summary>
/// <summary>
/// Utility.
/// Functions can not be classify easily.

public class Utility
{
    public static bool IsInstance<T>(object instance){
        return instance is T;
    }

	public static bool IsInstance(object instance, Type t){
		return instance.GetType() == t;
	}

	/// <summary>
	/// Counts the time.
	/// </summary>
	/// <returns>The time. </returns>
	/// <param name="second">Second.</param>
	public IEnumerator CountTime(float second,Callback cb)
	{
		yield return new WaitForSeconds(second);

		cb ();
	}
}

