// Code generated by protoc-gen-go.
// source: bbproto.proto
// DO NOT EDIT!

package bbproto

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type EUnitType int32

const (
	EUnitType_UALL   EUnitType = 0
	EUnitType_UFIRE  EUnitType = 1
	EUnitType_UWATER EUnitType = 2
	EUnitType_UWIND  EUnitType = 3
	EUnitType_ULIGHT EUnitType = 4
	EUnitType_UDARK  EUnitType = 5
	EUnitType_UNONE  EUnitType = 6
	EUnitType_UHeart EUnitType = 7
)

var EUnitType_name = map[int32]string{
	0: "UALL",
	1: "UFIRE",
	2: "UWATER",
	3: "UWIND",
	4: "ULIGHT",
	5: "UDARK",
	6: "UNONE",
	7: "UHeart",
}
var EUnitType_value = map[string]int32{
	"UALL":   0,
	"UFIRE":  1,
	"UWATER": 2,
	"UWIND":  3,
	"ULIGHT": 4,
	"UDARK":  5,
	"UNONE":  6,
	"UHeart": 7,
}

func (x EUnitType) Enum() *EUnitType {
	p := new(EUnitType)
	*p = x
	return p
}
func (x EUnitType) String() string {
	return proto.EnumName(EUnitType_name, int32(x))
}
func (x *EUnitType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EUnitType_value, data, "EUnitType")
	if err != nil {
		return err
	}
	*x = EUnitType(value)
	return nil
}

type EUnitRace int32

const (
	EUnitRace_ALL          EUnitRace = 0
	EUnitRace_HUMAN        EUnitRace = 1
	EUnitRace_UNDEAD       EUnitRace = 2
	EUnitRace_MYTHIC       EUnitRace = 3
	EUnitRace_BEAST        EUnitRace = 4
	EUnitRace_MONSTER      EUnitRace = 5
	EUnitRace_LEGEND       EUnitRace = 6
	EUnitRace_SCREAMCHEESE EUnitRace = 7
)

var EUnitRace_name = map[int32]string{
	0: "ALL",
	1: "HUMAN",
	2: "UNDEAD",
	3: "MYTHIC",
	4: "BEAST",
	5: "MONSTER",
	6: "LEGEND",
	7: "SCREAMCHEESE",
}
var EUnitRace_value = map[string]int32{
	"ALL":          0,
	"HUMAN":        1,
	"UNDEAD":       2,
	"MYTHIC":       3,
	"BEAST":        4,
	"MONSTER":      5,
	"LEGEND":       6,
	"SCREAMCHEESE": 7,
}

func (x EUnitRace) Enum() *EUnitRace {
	p := new(EUnitRace)
	*p = x
	return p
}
func (x EUnitRace) String() string {
	return proto.EnumName(EUnitRace_name, int32(x))
}
func (x *EUnitRace) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EUnitRace_value, data, "EUnitRace")
	if err != nil {
		return err
	}
	*x = EUnitRace(value)
	return nil
}

type EFriendState int32

const (
	EFriendState_ISFRIEND     EFriendState = 1
	EFriendState_FRIENDOUT    EFriendState = 2
	EFriendState_FRIENDIN     EFriendState = 3
	EFriendState_FRIENDHELPER EFriendState = 4
)

var EFriendState_name = map[int32]string{
	1: "ISFRIEND",
	2: "FRIENDOUT",
	3: "FRIENDIN",
	4: "FRIENDHELPER",
}
var EFriendState_value = map[string]int32{
	"ISFRIEND":     1,
	"FRIENDOUT":    2,
	"FRIENDIN":     3,
	"FRIENDHELPER": 4,
}

func (x EFriendState) Enum() *EFriendState {
	p := new(EFriendState)
	*p = x
	return p
}
func (x EFriendState) String() string {
	return proto.EnumName(EFriendState_name, int32(x))
}
func (x *EFriendState) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EFriendState_value, data, "EFriendState")
	if err != nil {
		return err
	}
	*x = EFriendState(value)
	return nil
}

type EQuestState int32

const (
	EQuestState_QS_NEW      EQuestState = 0
	EQuestState_QS_QUESTING EQuestState = 1
	EQuestState_QS_CLEARED  EQuestState = 2
)

var EQuestState_name = map[int32]string{
	0: "QS_NEW",
	1: "QS_QUESTING",
	2: "QS_CLEARED",
}
var EQuestState_value = map[string]int32{
	"QS_NEW":      0,
	"QS_QUESTING": 1,
	"QS_CLEARED":  2,
}

func (x EQuestState) Enum() *EQuestState {
	p := new(EQuestState)
	*p = x
	return p
}
func (x EQuestState) String() string {
	return proto.EnumName(EQuestState_name, int32(x))
}
func (x *EQuestState) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EQuestState_value, data, "EQuestState")
	if err != nil {
		return err
	}
	*x = EQuestState(value)
	return nil
}

type ETrapType int32

const (
	ETrapType_Move           ETrapType = 0
	ETrapType_StateException ETrapType = 1
	ETrapType_ChangeEnvir    ETrapType = 2
	ETrapType_Injured        ETrapType = 3
)

var ETrapType_name = map[int32]string{
	0: "Move",
	1: "StateException",
	2: "ChangeEnvir",
	3: "Injured",
}
var ETrapType_value = map[string]int32{
	"Move":           0,
	"StateException": 1,
	"ChangeEnvir":    2,
	"Injured":        3,
}

func (x ETrapType) Enum() *ETrapType {
	p := new(ETrapType)
	*p = x
	return p
}
func (x ETrapType) String() string {
	return proto.EnumName(ETrapType_name, int32(x))
}
func (x *ETrapType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ETrapType_value, data, "ETrapType")
	if err != nil {
		return err
	}
	*x = ETrapType(value)
	return nil
}

type EQuestGridType int32

const (
	EQuestGridType_Q_NONE     EQuestGridType = 0
	EQuestGridType_Q_TREATURE EQuestGridType = 1
	EQuestGridType_Q_ENEMY    EQuestGridType = 2
	EQuestGridType_Q_TRAP     EQuestGridType = 3
)

var EQuestGridType_name = map[int32]string{
	0: "Q_NONE",
	1: "Q_TREATURE",
	2: "Q_ENEMY",
	3: "Q_TRAP",
}
var EQuestGridType_value = map[string]int32{
	"Q_NONE":     0,
	"Q_TREATURE": 1,
	"Q_ENEMY":    2,
	"Q_TRAP":     3,
}

func (x EQuestGridType) Enum() *EQuestGridType {
	p := new(EQuestGridType)
	*p = x
	return p
}
func (x EQuestGridType) String() string {
	return proto.EnumName(EQuestGridType_name, int32(x))
}
func (x *EQuestGridType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EQuestGridType_value, data, "EQuestGridType")
	if err != nil {
		return err
	}
	*x = EQuestGridType(value)
	return nil
}

type EGridStar int32

const (
	EGridStar_GS_EMPTY       EGridStar = 0
	EGridStar_GS_STAR_1      EGridStar = 1
	EGridStar_GS_STAR_2      EGridStar = 2
	EGridStar_GS_STAR_3      EGridStar = 3
	EGridStar_GS_STAR_4      EGridStar = 4
	EGridStar_GS_STAR_5      EGridStar = 5
	EGridStar_GS_STAR_6      EGridStar = 6
	EGridStar_GS_KEY         EGridStar = 7
	EGridStar_GS_QUESTION    EGridStar = 8
	EGridStar_GS_EXCLAMATION EGridStar = 9
)

var EGridStar_name = map[int32]string{
	0: "GS_EMPTY",
	1: "GS_STAR_1",
	2: "GS_STAR_2",
	3: "GS_STAR_3",
	4: "GS_STAR_4",
	5: "GS_STAR_5",
	6: "GS_STAR_6",
	7: "GS_KEY",
	8: "GS_QUESTION",
	9: "GS_EXCLAMATION",
}
var EGridStar_value = map[string]int32{
	"GS_EMPTY":       0,
	"GS_STAR_1":      1,
	"GS_STAR_2":      2,
	"GS_STAR_3":      3,
	"GS_STAR_4":      4,
	"GS_STAR_5":      5,
	"GS_STAR_6":      6,
	"GS_KEY":         7,
	"GS_QUESTION":    8,
	"GS_EXCLAMATION": 9,
}

func (x EGridStar) Enum() *EGridStar {
	p := new(EGridStar)
	*p = x
	return p
}
func (x EGridStar) String() string {
	return proto.EnumName(EGridStar_name, int32(x))
}
func (x *EGridStar) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EGridStar_value, data, "EGridStar")
	if err != nil {
		return err
	}
	*x = EGridStar(value)
	return nil
}

type QuestBoostType int32

const (
	QuestBoostType_QB_BOOST_NONE     QuestBoostType = 0
	QuestBoostType_QB_BOOST_MONEY    QuestBoostType = 1
	QuestBoostType_QB_BOOST_EXP      QuestBoostType = 2
	QuestBoostType_QB_BOOST_DROPRATE QuestBoostType = 3
	QuestBoostType_QB_BOOST_DROPPLUS QuestBoostType = 4
)

var QuestBoostType_name = map[int32]string{
	0: "QB_BOOST_NONE",
	1: "QB_BOOST_MONEY",
	2: "QB_BOOST_EXP",
	3: "QB_BOOST_DROPRATE",
	4: "QB_BOOST_DROPPLUS",
}
var QuestBoostType_value = map[string]int32{
	"QB_BOOST_NONE":     0,
	"QB_BOOST_MONEY":    1,
	"QB_BOOST_EXP":      2,
	"QB_BOOST_DROPRATE": 3,
	"QB_BOOST_DROPPLUS": 4,
}

func (x QuestBoostType) Enum() *QuestBoostType {
	p := new(QuestBoostType)
	*p = x
	return p
}
func (x QuestBoostType) String() string {
	return proto.EnumName(QuestBoostType_name, int32(x))
}
func (x *QuestBoostType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(QuestBoostType_value, data, "QuestBoostType")
	if err != nil {
		return err
	}
	*x = QuestBoostType(value)
	return nil
}

// general response protocol
type ProtoHeader struct {
	ApiVer           *string `protobuf:"bytes,1,req,name=apiVer" json:"apiVer,omitempty"`
	SessionId        *string `protobuf:"bytes,2,opt,name=sessionId" json:"sessionId,omitempty"`
	UserId           *uint32 `protobuf:"varint,3,opt,name=userId" json:"userId,omitempty"`
	PacketId         *int32  `protobuf:"varint,4,opt,name=packetId" json:"packetId,omitempty"`
	Code             *int32  `protobuf:"varint,5,opt,name=code" json:"code,omitempty"`
	Error            *string `protobuf:"bytes,6,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProtoHeader) Reset()         { *m = ProtoHeader{} }
func (m *ProtoHeader) String() string { return proto.CompactTextString(m) }
func (*ProtoHeader) ProtoMessage()    {}

func (m *ProtoHeader) GetApiVer() string {
	if m != nil && m.ApiVer != nil {
		return *m.ApiVer
	}
	return ""
}

func (m *ProtoHeader) GetSessionId() string {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return ""
}

func (m *ProtoHeader) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *ProtoHeader) GetPacketId() int32 {
	if m != nil && m.PacketId != nil {
		return *m.PacketId
	}
	return 0
}

func (m *ProtoHeader) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *ProtoHeader) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

type FriendData struct {
	UserId            *uint32       `protobuf:"varint,1,opt,name=userId" json:"userId,omitempty"`
	FriendState       *EFriendState `protobuf:"varint,2,opt,name=friendState,enum=bbproto.EFriendState" json:"friendState,omitempty"`
	FriendStateUpdate *uint32       `protobuf:"varint,3,opt,name=friendStateUpdate" json:"friendStateUpdate,omitempty"`
	XXX_unrecognized  []byte        `json:"-"`
}

func (m *FriendData) Reset()         { *m = FriendData{} }
func (m *FriendData) String() string { return proto.CompactTextString(m) }
func (*FriendData) ProtoMessage()    {}

func (m *FriendData) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *FriendData) GetFriendState() EFriendState {
	if m != nil && m.FriendState != nil {
		return *m.FriendState
	}
	return EFriendState_ISFRIEND
}

func (m *FriendData) GetFriendStateUpdate() uint32 {
	if m != nil && m.FriendStateUpdate != nil {
		return *m.FriendStateUpdate
	}
	return 0
}

type FriendInfo struct {
	UserId            *uint32       `protobuf:"varint,1,opt,name=userId" json:"userId,omitempty"`
	NickName          *string       `protobuf:"bytes,2,opt,name=nickName" json:"nickName,omitempty"`
	Rank              *int32        `protobuf:"varint,3,opt,name=rank" json:"rank,omitempty"`
	LastPlayTime      *uint32       `protobuf:"varint,4,opt,name=lastPlayTime" json:"lastPlayTime,omitempty"`
	FriendState       *EFriendState `protobuf:"varint,5,opt,name=friendState,enum=bbproto.EFriendState" json:"friendState,omitempty"`
	FriendStateUpdate *uint32       `protobuf:"varint,6,opt,name=friendStateUpdate" json:"friendStateUpdate,omitempty"`
	FriendPoint       *int32        `protobuf:"varint,7,opt,name=friendPoint" json:"friendPoint,omitempty"`
	Unit              *UserUnit     `protobuf:"bytes,8,opt,name=unit" json:"unit,omitempty"`
	XXX_unrecognized  []byte        `json:"-"`
}

func (m *FriendInfo) Reset()         { *m = FriendInfo{} }
func (m *FriendInfo) String() string { return proto.CompactTextString(m) }
func (*FriendInfo) ProtoMessage()    {}

func (m *FriendInfo) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *FriendInfo) GetNickName() string {
	if m != nil && m.NickName != nil {
		return *m.NickName
	}
	return ""
}

func (m *FriendInfo) GetRank() int32 {
	if m != nil && m.Rank != nil {
		return *m.Rank
	}
	return 0
}

func (m *FriendInfo) GetLastPlayTime() uint32 {
	if m != nil && m.LastPlayTime != nil {
		return *m.LastPlayTime
	}
	return 0
}

func (m *FriendInfo) GetFriendState() EFriendState {
	if m != nil && m.FriendState != nil {
		return *m.FriendState
	}
	return EFriendState_ISFRIEND
}

func (m *FriendInfo) GetFriendStateUpdate() uint32 {
	if m != nil && m.FriendStateUpdate != nil {
		return *m.FriendStateUpdate
	}
	return 0
}

func (m *FriendInfo) GetFriendPoint() int32 {
	if m != nil && m.FriendPoint != nil {
		return *m.FriendPoint
	}
	return 0
}

func (m *FriendInfo) GetUnit() *UserUnit {
	if m != nil {
		return m.Unit
	}
	return nil
}

type FriendList struct {
	Friend           []*FriendInfo `protobuf:"bytes,1,rep,name=friend" json:"friend,omitempty"`
	Helper           []*FriendInfo `protobuf:"bytes,2,rep,name=helper" json:"helper,omitempty"`
	FriendIn         []*FriendInfo `protobuf:"bytes,3,rep,name=friendIn" json:"friendIn,omitempty"`
	FriendOut        []*FriendInfo `protobuf:"bytes,4,rep,name=friendOut" json:"friendOut,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *FriendList) Reset()         { *m = FriendList{} }
func (m *FriendList) String() string { return proto.CompactTextString(m) }
func (*FriendList) ProtoMessage()    {}

func (m *FriendList) GetFriend() []*FriendInfo {
	if m != nil {
		return m.Friend
	}
	return nil
}

func (m *FriendList) GetHelper() []*FriendInfo {
	if m != nil {
		return m.Helper
	}
	return nil
}

func (m *FriendList) GetFriendIn() []*FriendInfo {
	if m != nil {
		return m.FriendIn
	}
	return nil
}

func (m *FriendList) GetFriendOut() []*FriendInfo {
	if m != nil {
		return m.FriendOut
	}
	return nil
}

// -------------------------------------------------
type ReqGetFriend struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	GetFriend        *bool        `protobuf:"varint,2,opt,name=getFriend" json:"getFriend,omitempty"`
	GetHelper        *bool        `protobuf:"varint,3,opt,name=getHelper" json:"getHelper,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ReqGetFriend) Reset()         { *m = ReqGetFriend{} }
func (m *ReqGetFriend) String() string { return proto.CompactTextString(m) }
func (*ReqGetFriend) ProtoMessage()    {}

func (m *ReqGetFriend) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ReqGetFriend) GetGetFriend() bool {
	if m != nil && m.GetFriend != nil {
		return *m.GetFriend
	}
	return false
}

func (m *ReqGetFriend) GetGetHelper() bool {
	if m != nil && m.GetHelper != nil {
		return *m.GetHelper
	}
	return false
}

type RspGetFriend struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Friends          *FriendList  `protobuf:"bytes,2,opt,name=friends" json:"friends,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *RspGetFriend) Reset()         { *m = RspGetFriend{} }
func (m *RspGetFriend) String() string { return proto.CompactTextString(m) }
func (*RspGetFriend) ProtoMessage()    {}

func (m *RspGetFriend) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *RspGetFriend) GetFriends() *FriendList {
	if m != nil {
		return m.Friends
	}
	return nil
}

// -------------------------------------------------
type ReqFindFriend struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	FriendUid        *uint32      `protobuf:"varint,2,opt,name=friendUid" json:"friendUid,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ReqFindFriend) Reset()         { *m = ReqFindFriend{} }
func (m *ReqFindFriend) String() string { return proto.CompactTextString(m) }
func (*ReqFindFriend) ProtoMessage()    {}

func (m *ReqFindFriend) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ReqFindFriend) GetFriendUid() uint32 {
	if m != nil && m.FriendUid != nil {
		return *m.FriendUid
	}
	return 0
}

type RspFindFriend struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Friend           *UserInfo    `protobuf:"bytes,2,opt,name=friend" json:"friend,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *RspFindFriend) Reset()         { *m = RspFindFriend{} }
func (m *RspFindFriend) String() string { return proto.CompactTextString(m) }
func (*RspFindFriend) ProtoMessage()    {}

func (m *RspFindFriend) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *RspFindFriend) GetFriend() *UserInfo {
	if m != nil {
		return m.Friend
	}
	return nil
}

// -------------------------------------------------
type ReqAddFriend struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	FriendUid        *uint32      `protobuf:"varint,2,opt,name=friendUid" json:"friendUid,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ReqAddFriend) Reset()         { *m = ReqAddFriend{} }
func (m *ReqAddFriend) String() string { return proto.CompactTextString(m) }
func (*ReqAddFriend) ProtoMessage()    {}

func (m *ReqAddFriend) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ReqAddFriend) GetFriendUid() uint32 {
	if m != nil && m.FriendUid != nil {
		return *m.FriendUid
	}
	return 0
}

type RspAddFriend struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *RspAddFriend) Reset()         { *m = RspAddFriend{} }
func (m *RspAddFriend) String() string { return proto.CompactTextString(m) }
func (*RspAddFriend) ProtoMessage()    {}

func (m *RspAddFriend) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

// -------------------------------------------------
type ReqDelFriend struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	FriendUid        *uint32      `protobuf:"varint,2,opt,name=friendUid" json:"friendUid,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ReqDelFriend) Reset()         { *m = ReqDelFriend{} }
func (m *ReqDelFriend) String() string { return proto.CompactTextString(m) }
func (*ReqDelFriend) ProtoMessage()    {}

func (m *ReqDelFriend) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ReqDelFriend) GetFriendUid() uint32 {
	if m != nil && m.FriendUid != nil {
		return *m.FriendUid
	}
	return 0
}

type RspDelFriend struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *RspDelFriend) Reset()         { *m = RspDelFriend{} }
func (m *RspDelFriend) String() string { return proto.CompactTextString(m) }
func (*RspDelFriend) ProtoMessage()    {}

func (m *RspDelFriend) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

// -------------------------------------------------
type ReqAcceptFriend struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	FriendUid        *uint32      `protobuf:"varint,2,opt,name=friendUid" json:"friendUid,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ReqAcceptFriend) Reset()         { *m = ReqAcceptFriend{} }
func (m *ReqAcceptFriend) String() string { return proto.CompactTextString(m) }
func (*ReqAcceptFriend) ProtoMessage()    {}

func (m *ReqAcceptFriend) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ReqAcceptFriend) GetFriendUid() uint32 {
	if m != nil && m.FriendUid != nil {
		return *m.FriendUid
	}
	return 0
}

type RspAcceptFriend struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *RspAcceptFriend) Reset()         { *m = RspAcceptFriend{} }
func (m *RspAcceptFriend) String() string { return proto.CompactTextString(m) }
func (*RspAcceptFriend) ProtoMessage()    {}

func (m *RspAcceptFriend) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type QuestStatus struct {
	State            *EQuestState `protobuf:"varint,1,opt,name=state,enum=bbproto.EQuestState" json:"state,omitempty"`
	PlayTime         []uint32     `protobuf:"varint,2,rep,name=playTime" json:"playTime,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *QuestStatus) Reset()         { *m = QuestStatus{} }
func (m *QuestStatus) String() string { return proto.CompactTextString(m) }
func (*QuestStatus) ProtoMessage()    {}

func (m *QuestStatus) GetState() EQuestState {
	if m != nil && m.State != nil {
		return *m.State
	}
	return EQuestState_QS_NEW
}

func (m *QuestStatus) GetPlayTime() []uint32 {
	if m != nil {
		return m.PlayTime
	}
	return nil
}

type QuestLog struct {
	QuestId          *uint32      `protobuf:"varint,1,opt,name=questId" json:"questId,omitempty"`
	StartTime        *uint32      `protobuf:"varint,2,opt,name=startTime" json:"startTime,omitempty"`
	EndTime          *uint32      `protobuf:"varint,3,opt,name=endTime" json:"endTime,omitempty"`
	HelperUserId     *uint32      `protobuf:"varint,4,opt,name=helperUserId" json:"helperUserId,omitempty"`
	HelperUnit       *UserUnit    `protobuf:"bytes,5,opt,name=helperUnit" json:"helperUnit,omitempty"`
	CurrentParty     *int32       `protobuf:"varint,6,opt,name=currentParty" json:"currentParty,omitempty"`
	DropUnits        []*DropUnit  `protobuf:"bytes,7,rep,name=dropUnits" json:"dropUnits,omitempty"`
	GetUnit          []*UserUnit  `protobuf:"bytes,8,rep,name=getUnit" json:"getUnit,omitempty"`
	GetExp           *int32       `protobuf:"varint,9,opt,name=getExp" json:"getExp,omitempty"`
	GetMoney         *int32       `protobuf:"varint,10,opt,name=getMoney" json:"getMoney,omitempty"`
	GetFriendPoint   *int32       `protobuf:"varint,11,opt,name=getFriendPoint" json:"getFriendPoint,omitempty"`
	ContinueTimes    *int32       `protobuf:"varint,12,opt,name=continueTimes" json:"continueTimes,omitempty"`
	State            *EQuestState `protobuf:"varint,13,opt,name=state,enum=bbproto.EQuestState" json:"state,omitempty"`
	PlayTotal        *int32       `protobuf:"varint,14,opt,name=playTotal" json:"playTotal,omitempty"`
	PlayToday        *int32       `protobuf:"varint,15,opt,name=playToday" json:"playToday,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *QuestLog) Reset()         { *m = QuestLog{} }
func (m *QuestLog) String() string { return proto.CompactTextString(m) }
func (*QuestLog) ProtoMessage()    {}

func (m *QuestLog) GetQuestId() uint32 {
	if m != nil && m.QuestId != nil {
		return *m.QuestId
	}
	return 0
}

func (m *QuestLog) GetStartTime() uint32 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

func (m *QuestLog) GetEndTime() uint32 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

func (m *QuestLog) GetHelperUserId() uint32 {
	if m != nil && m.HelperUserId != nil {
		return *m.HelperUserId
	}
	return 0
}

func (m *QuestLog) GetHelperUnit() *UserUnit {
	if m != nil {
		return m.HelperUnit
	}
	return nil
}

func (m *QuestLog) GetCurrentParty() int32 {
	if m != nil && m.CurrentParty != nil {
		return *m.CurrentParty
	}
	return 0
}

func (m *QuestLog) GetDropUnits() []*DropUnit {
	if m != nil {
		return m.DropUnits
	}
	return nil
}

func (m *QuestLog) GetGetUnit() []*UserUnit {
	if m != nil {
		return m.GetUnit
	}
	return nil
}

func (m *QuestLog) GetGetExp() int32 {
	if m != nil && m.GetExp != nil {
		return *m.GetExp
	}
	return 0
}

func (m *QuestLog) GetGetMoney() int32 {
	if m != nil && m.GetMoney != nil {
		return *m.GetMoney
	}
	return 0
}

func (m *QuestLog) GetGetFriendPoint() int32 {
	if m != nil && m.GetFriendPoint != nil {
		return *m.GetFriendPoint
	}
	return 0
}

func (m *QuestLog) GetContinueTimes() int32 {
	if m != nil && m.ContinueTimes != nil {
		return *m.ContinueTimes
	}
	return 0
}

func (m *QuestLog) GetState() EQuestState {
	if m != nil && m.State != nil {
		return *m.State
	}
	return EQuestState_QS_NEW
}

func (m *QuestLog) GetPlayTotal() int32 {
	if m != nil && m.PlayTotal != nil {
		return *m.PlayTotal
	}
	return 0
}

func (m *QuestLog) GetPlayToday() int32 {
	if m != nil && m.PlayToday != nil {
		return *m.PlayToday
	}
	return 0
}

// ----------------------Quest config data-----------------------------
type NumRange struct {
	Min              *int32 `protobuf:"varint,1,opt,name=min" json:"min,omitempty"`
	Max              *int32 `protobuf:"varint,2,opt,name=max" json:"max,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *NumRange) Reset()         { *m = NumRange{} }
func (m *NumRange) String() string { return proto.CompactTextString(m) }
func (*NumRange) ProtoMessage()    {}

func (m *NumRange) GetMin() int32 {
	if m != nil && m.Min != nil {
		return *m.Min
	}
	return 0
}

func (m *NumRange) GetMax() int32 {
	if m != nil && m.Max != nil {
		return *m.Max
	}
	return 0
}

type ColorPercent struct {
	Color            *EUnitType `protobuf:"varint,1,opt,name=color,enum=bbproto.EUnitType" json:"color,omitempty"`
	Percent          *float32   `protobuf:"fixed32,2,opt,name=percent" json:"percent,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *ColorPercent) Reset()         { *m = ColorPercent{} }
func (m *ColorPercent) String() string { return proto.CompactTextString(m) }
func (*ColorPercent) ProtoMessage()    {}

func (m *ColorPercent) GetColor() EUnitType {
	if m != nil && m.Color != nil {
		return *m.Color
	}
	return EUnitType_UALL
}

func (m *ColorPercent) GetPercent() float32 {
	if m != nil && m.Percent != nil {
		return *m.Percent
	}
	return 0
}

type StarConfig struct {
	Repeat           *int32     `protobuf:"varint,1,opt,name=repeat" json:"repeat,omitempty"`
	Star             *EGridStar `protobuf:"varint,2,opt,name=star,enum=bbproto.EGridStar" json:"star,omitempty"`
	Coin             *NumRange  `protobuf:"bytes,3,opt,name=coin" json:"coin,omitempty"`
	EnemyPool        []uint32   `protobuf:"varint,4,rep,name=enemyPool" json:"enemyPool,omitempty"`
	EnemyNum         *NumRange  `protobuf:"bytes,5,opt,name=enemyNum" json:"enemyNum,omitempty"`
	Trap             []uint32   `protobuf:"varint,6,rep,name=trap" json:"trap,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *StarConfig) Reset()         { *m = StarConfig{} }
func (m *StarConfig) String() string { return proto.CompactTextString(m) }
func (*StarConfig) ProtoMessage()    {}

func (m *StarConfig) GetRepeat() int32 {
	if m != nil && m.Repeat != nil {
		return *m.Repeat
	}
	return 0
}

func (m *StarConfig) GetStar() EGridStar {
	if m != nil && m.Star != nil {
		return *m.Star
	}
	return EGridStar_GS_EMPTY
}

func (m *StarConfig) GetCoin() *NumRange {
	if m != nil {
		return m.Coin
	}
	return nil
}

func (m *StarConfig) GetEnemyPool() []uint32 {
	if m != nil {
		return m.EnemyPool
	}
	return nil
}

func (m *StarConfig) GetEnemyNum() *NumRange {
	if m != nil {
		return m.EnemyNum
	}
	return nil
}

func (m *StarConfig) GetTrap() []uint32 {
	if m != nil {
		return m.Trap
	}
	return nil
}

type QuestFloorConfig struct {
	Version          *int32        `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	TreasureNum      *int32        `protobuf:"varint,2,opt,name=treasureNum" json:"treasureNum,omitempty"`
	TrapNum          *int32        `protobuf:"varint,3,opt,name=trapNum" json:"trapNum,omitempty"`
	EnemyNum         *int32        `protobuf:"varint,4,opt,name=enemyNum" json:"enemyNum,omitempty"`
	Stars            []*StarConfig `protobuf:"bytes,5,rep,name=stars" json:"stars,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *QuestFloorConfig) Reset()         { *m = QuestFloorConfig{} }
func (m *QuestFloorConfig) String() string { return proto.CompactTextString(m) }
func (*QuestFloorConfig) ProtoMessage()    {}

func (m *QuestFloorConfig) GetVersion() int32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *QuestFloorConfig) GetTreasureNum() int32 {
	if m != nil && m.TreasureNum != nil {
		return *m.TreasureNum
	}
	return 0
}

func (m *QuestFloorConfig) GetTrapNum() int32 {
	if m != nil && m.TrapNum != nil {
		return *m.TrapNum
	}
	return 0
}

func (m *QuestFloorConfig) GetEnemyNum() int32 {
	if m != nil && m.EnemyNum != nil {
		return *m.EnemyNum
	}
	return 0
}

func (m *QuestFloorConfig) GetStars() []*StarConfig {
	if m != nil {
		return m.Stars
	}
	return nil
}

type QuestConfig struct {
	QuestId          *uint32             `protobuf:"varint,1,opt,name=questId" json:"questId,omitempty"`
	Boss             []*EnemyInfoConf    `protobuf:"bytes,2,rep,name=boss" json:"boss,omitempty"`
	Enemys           []*EnemyInfoConf    `protobuf:"bytes,3,rep,name=enemys" json:"enemys,omitempty"`
	Colors           []*ColorPercent     `protobuf:"bytes,4,rep,name=colors" json:"colors,omitempty"`
	Floors           []*QuestFloorConfig `protobuf:"bytes,5,rep,name=floors" json:"floors,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *QuestConfig) Reset()         { *m = QuestConfig{} }
func (m *QuestConfig) String() string { return proto.CompactTextString(m) }
func (*QuestConfig) ProtoMessage()    {}

func (m *QuestConfig) GetQuestId() uint32 {
	if m != nil && m.QuestId != nil {
		return *m.QuestId
	}
	return 0
}

func (m *QuestConfig) GetBoss() []*EnemyInfoConf {
	if m != nil {
		return m.Boss
	}
	return nil
}

func (m *QuestConfig) GetEnemys() []*EnemyInfoConf {
	if m != nil {
		return m.Enemys
	}
	return nil
}

func (m *QuestConfig) GetColors() []*ColorPercent {
	if m != nil {
		return m.Colors
	}
	return nil
}

func (m *QuestConfig) GetFloors() []*QuestFloorConfig {
	if m != nil {
		return m.Floors
	}
	return nil
}

// -------------------------QuestData------------------------------
type EnemyInfo struct {
	EnemyId          *uint32    `protobuf:"varint,1,opt,name=enemyId" json:"enemyId,omitempty"`
	UnitId           *uint32    `protobuf:"varint,2,opt,name=unitId" json:"unitId,omitempty"`
	Type             *EUnitType `protobuf:"varint,3,opt,name=type,enum=bbproto.EUnitType" json:"type,omitempty"`
	Hp               *int32     `protobuf:"varint,4,opt,name=hp" json:"hp,omitempty"`
	Attack           *int32     `protobuf:"varint,5,opt,name=attack" json:"attack,omitempty"`
	Defense          *int32     `protobuf:"varint,6,opt,name=defense" json:"defense,omitempty"`
	NextAttack       *int32     `protobuf:"varint,7,opt,name=nextAttack" json:"nextAttack,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *EnemyInfo) Reset()         { *m = EnemyInfo{} }
func (m *EnemyInfo) String() string { return proto.CompactTextString(m) }
func (*EnemyInfo) ProtoMessage()    {}

func (m *EnemyInfo) GetEnemyId() uint32 {
	if m != nil && m.EnemyId != nil {
		return *m.EnemyId
	}
	return 0
}

func (m *EnemyInfo) GetUnitId() uint32 {
	if m != nil && m.UnitId != nil {
		return *m.UnitId
	}
	return 0
}

func (m *EnemyInfo) GetType() EUnitType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return EUnitType_UALL
}

func (m *EnemyInfo) GetHp() int32 {
	if m != nil && m.Hp != nil {
		return *m.Hp
	}
	return 0
}

func (m *EnemyInfo) GetAttack() int32 {
	if m != nil && m.Attack != nil {
		return *m.Attack
	}
	return 0
}

func (m *EnemyInfo) GetDefense() int32 {
	if m != nil && m.Defense != nil {
		return *m.Defense
	}
	return 0
}

func (m *EnemyInfo) GetNextAttack() int32 {
	if m != nil && m.NextAttack != nil {
		return *m.NextAttack
	}
	return 0
}

type EnemyInfoConf struct {
	Enemy            *EnemyInfo `protobuf:"bytes,1,opt,name=enemy" json:"enemy,omitempty"`
	DropUnitId       *uint32    `protobuf:"varint,2,opt,name=dropUnitId" json:"dropUnitId,omitempty"`
	DropUnitLevel    *int32     `protobuf:"varint,3,opt,name=dropUnitLevel" json:"dropUnitLevel,omitempty"`
	DropRate         *float32   `protobuf:"fixed32,4,opt,name=dropRate" json:"dropRate,omitempty"`
	AddHpRate        *float32   `protobuf:"fixed32,5,opt,name=addHpRate" json:"addHpRate,omitempty"`
	AddAttackRate    *float32   `protobuf:"fixed32,6,opt,name=addAttackRate" json:"addAttackRate,omitempty"`
	AddDefenceRate   *float32   `protobuf:"fixed32,7,opt,name=addDefenceRate" json:"addDefenceRate,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *EnemyInfoConf) Reset()         { *m = EnemyInfoConf{} }
func (m *EnemyInfoConf) String() string { return proto.CompactTextString(m) }
func (*EnemyInfoConf) ProtoMessage()    {}

func (m *EnemyInfoConf) GetEnemy() *EnemyInfo {
	if m != nil {
		return m.Enemy
	}
	return nil
}

func (m *EnemyInfoConf) GetDropUnitId() uint32 {
	if m != nil && m.DropUnitId != nil {
		return *m.DropUnitId
	}
	return 0
}

func (m *EnemyInfoConf) GetDropUnitLevel() int32 {
	if m != nil && m.DropUnitLevel != nil {
		return *m.DropUnitLevel
	}
	return 0
}

func (m *EnemyInfoConf) GetDropRate() float32 {
	if m != nil && m.DropRate != nil {
		return *m.DropRate
	}
	return 0
}

func (m *EnemyInfoConf) GetAddHpRate() float32 {
	if m != nil && m.AddHpRate != nil {
		return *m.AddHpRate
	}
	return 0
}

func (m *EnemyInfoConf) GetAddAttackRate() float32 {
	if m != nil && m.AddAttackRate != nil {
		return *m.AddAttackRate
	}
	return 0
}

func (m *EnemyInfoConf) GetAddDefenceRate() float32 {
	if m != nil && m.AddDefenceRate != nil {
		return *m.AddDefenceRate
	}
	return 0
}

type DropUnit struct {
	DropId           *uint32 `protobuf:"varint,1,opt,name=dropId" json:"dropId,omitempty"`
	UnitId           *uint32 `protobuf:"varint,2,opt,name=unitId" json:"unitId,omitempty"`
	Level            *int32  `protobuf:"varint,3,opt,name=level" json:"level,omitempty"`
	AddHp            *int32  `protobuf:"varint,4,opt,name=addHp" json:"addHp,omitempty"`
	AddAttack        *int32  `protobuf:"varint,5,opt,name=addAttack" json:"addAttack,omitempty"`
	AddDefence       *int32  `protobuf:"varint,6,opt,name=addDefence" json:"addDefence,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DropUnit) Reset()         { *m = DropUnit{} }
func (m *DropUnit) String() string { return proto.CompactTextString(m) }
func (*DropUnit) ProtoMessage()    {}

func (m *DropUnit) GetDropId() uint32 {
	if m != nil && m.DropId != nil {
		return *m.DropId
	}
	return 0
}

func (m *DropUnit) GetUnitId() uint32 {
	if m != nil && m.UnitId != nil {
		return *m.UnitId
	}
	return 0
}

func (m *DropUnit) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *DropUnit) GetAddHp() int32 {
	if m != nil && m.AddHp != nil {
		return *m.AddHp
	}
	return 0
}

func (m *DropUnit) GetAddAttack() int32 {
	if m != nil && m.AddAttack != nil {
		return *m.AddAttack
	}
	return 0
}

func (m *DropUnit) GetAddDefence() int32 {
	if m != nil && m.AddDefence != nil {
		return *m.AddDefence
	}
	return 0
}

type QuestGrid struct {
	Position         *int32          `protobuf:"varint,1,opt,name=position" json:"position,omitempty"`
	Star             *EGridStar      `protobuf:"varint,2,opt,name=star,enum=bbproto.EGridStar" json:"star,omitempty"`
	Color            *int32          `protobuf:"varint,3,opt,name=color" json:"color,omitempty"`
	Type             *EQuestGridType `protobuf:"varint,4,opt,name=type,enum=bbproto.EQuestGridType" json:"type,omitempty"`
	EnemyId          []uint32        `protobuf:"varint,5,rep,name=enemyId" json:"enemyId,omitempty"`
	DropId           []uint32        `protobuf:"varint,6,rep,name=dropId" json:"dropId,omitempty"`
	Coins            *int32          `protobuf:"varint,7,opt,name=coins" json:"coins,omitempty"`
	TrapId           *uint32         `protobuf:"varint,8,opt,name=trapId" json:"trapId,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *QuestGrid) Reset()         { *m = QuestGrid{} }
func (m *QuestGrid) String() string { return proto.CompactTextString(m) }
func (*QuestGrid) ProtoMessage()    {}

func (m *QuestGrid) GetPosition() int32 {
	if m != nil && m.Position != nil {
		return *m.Position
	}
	return 0
}

func (m *QuestGrid) GetStar() EGridStar {
	if m != nil && m.Star != nil {
		return *m.Star
	}
	return EGridStar_GS_EMPTY
}

func (m *QuestGrid) GetColor() int32 {
	if m != nil && m.Color != nil {
		return *m.Color
	}
	return 0
}

func (m *QuestGrid) GetType() EQuestGridType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return EQuestGridType_Q_NONE
}

func (m *QuestGrid) GetEnemyId() []uint32 {
	if m != nil {
		return m.EnemyId
	}
	return nil
}

func (m *QuestGrid) GetDropId() []uint32 {
	if m != nil {
		return m.DropId
	}
	return nil
}

func (m *QuestGrid) GetCoins() int32 {
	if m != nil && m.Coins != nil {
		return *m.Coins
	}
	return 0
}

func (m *QuestGrid) GetTrapId() uint32 {
	if m != nil && m.TrapId != nil {
		return *m.TrapId
	}
	return 0
}

type QuestFloor struct {
	GridInfo         []*QuestGrid `protobuf:"bytes,1,rep,name=gridInfo" json:"gridInfo,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *QuestFloor) Reset()         { *m = QuestFloor{} }
func (m *QuestFloor) String() string { return proto.CompactTextString(m) }
func (*QuestFloor) ProtoMessage()    {}

func (m *QuestFloor) GetGridInfo() []*QuestGrid {
	if m != nil {
		return m.GridInfo
	}
	return nil
}

type QuestDungeonData struct {
	QuestId          *uint32       `protobuf:"varint,1,opt,name=questId" json:"questId,omitempty"`
	Boss             []*EnemyInfo  `protobuf:"bytes,2,rep,name=boss" json:"boss,omitempty"`
	Enemys           []*EnemyInfo  `protobuf:"bytes,3,rep,name=enemys" json:"enemys,omitempty"`
	Colors           []byte        `protobuf:"bytes,4,opt,name=colors" json:"colors,omitempty"`
	Drop             []*DropUnit   `protobuf:"bytes,5,rep,name=drop" json:"drop,omitempty"`
	Floors           []*QuestFloor `protobuf:"bytes,6,rep,name=floors" json:"floors,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *QuestDungeonData) Reset()         { *m = QuestDungeonData{} }
func (m *QuestDungeonData) String() string { return proto.CompactTextString(m) }
func (*QuestDungeonData) ProtoMessage()    {}

func (m *QuestDungeonData) GetQuestId() uint32 {
	if m != nil && m.QuestId != nil {
		return *m.QuestId
	}
	return 0
}

func (m *QuestDungeonData) GetBoss() []*EnemyInfo {
	if m != nil {
		return m.Boss
	}
	return nil
}

func (m *QuestDungeonData) GetEnemys() []*EnemyInfo {
	if m != nil {
		return m.Enemys
	}
	return nil
}

func (m *QuestDungeonData) GetColors() []byte {
	if m != nil {
		return m.Colors
	}
	return nil
}

func (m *QuestDungeonData) GetDrop() []*DropUnit {
	if m != nil {
		return m.Drop
	}
	return nil
}

func (m *QuestDungeonData) GetFloors() []*QuestFloor {
	if m != nil {
		return m.Floors
	}
	return nil
}

// ============== QuestMapData -  client data also used=======================//
type Position struct {
	X                *int32 `protobuf:"varint,1,opt,name=x" json:"x,omitempty"`
	Y                *int32 `protobuf:"varint,2,opt,name=y" json:"y,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}

func (m *Position) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *Position) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

type QuestInfo struct {
	Id               *uint32      `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	State            *EQuestState `protobuf:"varint,2,opt,name=state,enum=bbproto.EQuestState" json:"state,omitempty"`
	No               *int32       `protobuf:"varint,3,opt,name=no" json:"no,omitempty"`
	Name             *string      `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Story            *string      `protobuf:"bytes,5,opt,name=story" json:"story,omitempty"`
	Stamina          *int32       `protobuf:"varint,6,opt,name=stamina" json:"stamina,omitempty"`
	Floor            *int32       `protobuf:"varint,7,opt,name=floor" json:"floor,omitempty"`
	RewardExp        *int32       `protobuf:"varint,8,opt,name=rewardExp" json:"rewardExp,omitempty"`
	RewardMoney      *int32       `protobuf:"varint,9,opt,name=rewardMoney" json:"rewardMoney,omitempty"`
	BossId           []uint32     `protobuf:"varint,10,rep,name=bossId" json:"bossId,omitempty"`
	EnemyId          []uint32     `protobuf:"varint,11,rep,name=enemyId" json:"enemyId,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *QuestInfo) Reset()         { *m = QuestInfo{} }
func (m *QuestInfo) String() string { return proto.CompactTextString(m) }
func (*QuestInfo) ProtoMessage()    {}

func (m *QuestInfo) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *QuestInfo) GetState() EQuestState {
	if m != nil && m.State != nil {
		return *m.State
	}
	return EQuestState_QS_NEW
}

func (m *QuestInfo) GetNo() int32 {
	if m != nil && m.No != nil {
		return *m.No
	}
	return 0
}

func (m *QuestInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *QuestInfo) GetStory() string {
	if m != nil && m.Story != nil {
		return *m.Story
	}
	return ""
}

func (m *QuestInfo) GetStamina() int32 {
	if m != nil && m.Stamina != nil {
		return *m.Stamina
	}
	return 0
}

func (m *QuestInfo) GetFloor() int32 {
	if m != nil && m.Floor != nil {
		return *m.Floor
	}
	return 0
}

func (m *QuestInfo) GetRewardExp() int32 {
	if m != nil && m.RewardExp != nil {
		return *m.RewardExp
	}
	return 0
}

func (m *QuestInfo) GetRewardMoney() int32 {
	if m != nil && m.RewardMoney != nil {
		return *m.RewardMoney
	}
	return 0
}

func (m *QuestInfo) GetBossId() []uint32 {
	if m != nil {
		return m.BossId
	}
	return nil
}

func (m *QuestInfo) GetEnemyId() []uint32 {
	if m != nil {
		return m.EnemyId
	}
	return nil
}

type QuestBoost struct {
	Type             *QuestBoostType `protobuf:"varint,1,opt,name=type,enum=bbproto.QuestBoostType" json:"type,omitempty"`
	Value            *int32          `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *QuestBoost) Reset()         { *m = QuestBoost{} }
func (m *QuestBoost) String() string { return proto.CompactTextString(m) }
func (*QuestBoost) ProtoMessage()    {}

func (m *QuestBoost) GetType() QuestBoostType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return QuestBoostType_QB_BOOST_NONE
}

func (m *QuestBoost) GetValue() int32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

type StageInfo struct {
	Version          *int32       `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Id               *uint32      `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	State            *EQuestState `protobuf:"varint,3,opt,name=state,enum=bbproto.EQuestState" json:"state,omitempty"`
	Type             *int32       `protobuf:"varint,4,opt,name=type" json:"type,omitempty"`
	StageName        *string      `protobuf:"bytes,5,opt,name=stageName" json:"stageName,omitempty"`
	Description      *string      `protobuf:"bytes,6,opt,name=description" json:"description,omitempty"`
	StartTime        *uint32      `protobuf:"varint,7,opt,name=startTime" json:"startTime,omitempty"`
	EndTime          *uint32      `protobuf:"varint,8,opt,name=endTime" json:"endTime,omitempty"`
	Boost            *QuestBoost  `protobuf:"bytes,9,opt,name=boost" json:"boost,omitempty"`
	Pos              *Position    `protobuf:"bytes,10,opt,name=pos" json:"pos,omitempty"`
	Quests           []*QuestInfo `protobuf:"bytes,11,rep,name=quests" json:"quests,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *StageInfo) Reset()         { *m = StageInfo{} }
func (m *StageInfo) String() string { return proto.CompactTextString(m) }
func (*StageInfo) ProtoMessage()    {}

func (m *StageInfo) GetVersion() int32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *StageInfo) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *StageInfo) GetState() EQuestState {
	if m != nil && m.State != nil {
		return *m.State
	}
	return EQuestState_QS_NEW
}

func (m *StageInfo) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *StageInfo) GetStageName() string {
	if m != nil && m.StageName != nil {
		return *m.StageName
	}
	return ""
}

func (m *StageInfo) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *StageInfo) GetStartTime() uint32 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

func (m *StageInfo) GetEndTime() uint32 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

func (m *StageInfo) GetBoost() *QuestBoost {
	if m != nil {
		return m.Boost
	}
	return nil
}

func (m *StageInfo) GetPos() *Position {
	if m != nil {
		return m.Pos
	}
	return nil
}

func (m *StageInfo) GetQuests() []*QuestInfo {
	if m != nil {
		return m.Quests
	}
	return nil
}

type CityInfo struct {
	Version          *int32       `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Id               *uint32      `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	State            *int32       `protobuf:"varint,3,opt,name=state" json:"state,omitempty"`
	CityName         *string      `protobuf:"bytes,4,opt,name=cityName" json:"cityName,omitempty"`
	Description      *string      `protobuf:"bytes,5,opt,name=description" json:"description,omitempty"`
	Pos              *Position    `protobuf:"bytes,6,opt,name=pos" json:"pos,omitempty"`
	Stages           []*StageInfo `protobuf:"bytes,7,rep,name=stages" json:"stages,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *CityInfo) Reset()         { *m = CityInfo{} }
func (m *CityInfo) String() string { return proto.CompactTextString(m) }
func (*CityInfo) ProtoMessage()    {}

func (m *CityInfo) GetVersion() int32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *CityInfo) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *CityInfo) GetState() int32 {
	if m != nil && m.State != nil {
		return *m.State
	}
	return 0
}

func (m *CityInfo) GetCityName() string {
	if m != nil && m.CityName != nil {
		return *m.CityName
	}
	return ""
}

func (m *CityInfo) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *CityInfo) GetPos() *Position {
	if m != nil {
		return m.Pos
	}
	return nil
}

func (m *CityInfo) GetStages() []*StageInfo {
	if m != nil {
		return m.Stages
	}
	return nil
}

type WorldMapInfo struct {
	Version          *int32      `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Id               *uint32     `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Citys            []*CityInfo `protobuf:"bytes,3,rep,name=citys" json:"citys,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *WorldMapInfo) Reset()         { *m = WorldMapInfo{} }
func (m *WorldMapInfo) String() string { return proto.CompactTextString(m) }
func (*WorldMapInfo) ProtoMessage()    {}

func (m *WorldMapInfo) GetVersion() int32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *WorldMapInfo) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *WorldMapInfo) GetCitys() []*CityInfo {
	if m != nil {
		return m.Citys
	}
	return nil
}

type ReqStartQuest struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	StageId          *uint32      `protobuf:"varint,2,opt,name=stageId" json:"stageId,omitempty"`
	QuestId          *uint32      `protobuf:"varint,3,opt,name=questId" json:"questId,omitempty"`
	HelperUserId     *uint32      `protobuf:"varint,4,opt,name=helperUserId" json:"helperUserId,omitempty"`
	HelperUnit       *UserUnit    `protobuf:"bytes,5,opt,name=helperUnit" json:"helperUnit,omitempty"`
	CurrentParty     *int32       `protobuf:"varint,6,opt,name=currentParty" json:"currentParty,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ReqStartQuest) Reset()         { *m = ReqStartQuest{} }
func (m *ReqStartQuest) String() string { return proto.CompactTextString(m) }
func (*ReqStartQuest) ProtoMessage()    {}

func (m *ReqStartQuest) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ReqStartQuest) GetStageId() uint32 {
	if m != nil && m.StageId != nil {
		return *m.StageId
	}
	return 0
}

func (m *ReqStartQuest) GetQuestId() uint32 {
	if m != nil && m.QuestId != nil {
		return *m.QuestId
	}
	return 0
}

func (m *ReqStartQuest) GetHelperUserId() uint32 {
	if m != nil && m.HelperUserId != nil {
		return *m.HelperUserId
	}
	return 0
}

func (m *ReqStartQuest) GetHelperUnit() *UserUnit {
	if m != nil {
		return m.HelperUnit
	}
	return nil
}

func (m *ReqStartQuest) GetCurrentParty() int32 {
	if m != nil && m.CurrentParty != nil {
		return *m.CurrentParty
	}
	return 0
}

type RspStartQuest struct {
	Header           *ProtoHeader      `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	StaminaNow       *int32            `protobuf:"varint,2,opt,name=staminaNow" json:"staminaNow,omitempty"`
	StaminaRecover   *uint32           `protobuf:"varint,3,opt,name=staminaRecover" json:"staminaRecover,omitempty"`
	DungeonData      *QuestDungeonData `protobuf:"bytes,4,opt,name=dungeonData" json:"dungeonData,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *RspStartQuest) Reset()         { *m = RspStartQuest{} }
func (m *RspStartQuest) String() string { return proto.CompactTextString(m) }
func (*RspStartQuest) ProtoMessage()    {}

func (m *RspStartQuest) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *RspStartQuest) GetStaminaNow() int32 {
	if m != nil && m.StaminaNow != nil {
		return *m.StaminaNow
	}
	return 0
}

func (m *RspStartQuest) GetStaminaRecover() uint32 {
	if m != nil && m.StaminaRecover != nil {
		return *m.StaminaRecover
	}
	return 0
}

func (m *RspStartQuest) GetDungeonData() *QuestDungeonData {
	if m != nil {
		return m.DungeonData
	}
	return nil
}

type ReqClearQuest struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	QuestId          *uint32      `protobuf:"varint,2,opt,name=questId" json:"questId,omitempty"`
	SecurityKey      *uint32      `protobuf:"varint,3,opt,name=securityKey" json:"securityKey,omitempty"`
	GetMoney         *int32       `protobuf:"varint,4,opt,name=getMoney" json:"getMoney,omitempty"`
	GetUnit          []*DropUnit  `protobuf:"bytes,5,rep,name=getUnit" json:"getUnit,omitempty"`
	HitGrid          []uint32     `protobuf:"varint,6,rep,name=hitGrid" json:"hitGrid,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ReqClearQuest) Reset()         { *m = ReqClearQuest{} }
func (m *ReqClearQuest) String() string { return proto.CompactTextString(m) }
func (*ReqClearQuest) ProtoMessage()    {}

func (m *ReqClearQuest) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ReqClearQuest) GetQuestId() uint32 {
	if m != nil && m.QuestId != nil {
		return *m.QuestId
	}
	return 0
}

func (m *ReqClearQuest) GetSecurityKey() uint32 {
	if m != nil && m.SecurityKey != nil {
		return *m.SecurityKey
	}
	return 0
}

func (m *ReqClearQuest) GetGetMoney() int32 {
	if m != nil && m.GetMoney != nil {
		return *m.GetMoney
	}
	return 0
}

func (m *ReqClearQuest) GetGetUnit() []*DropUnit {
	if m != nil {
		return m.GetUnit
	}
	return nil
}

func (m *ReqClearQuest) GetHitGrid() []uint32 {
	if m != nil {
		return m.HitGrid
	}
	return nil
}

type RspClearQuest struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Rank             *int32       `protobuf:"varint,2,opt,name=rank" json:"rank,omitempty"`
	Exp              *int32       `protobuf:"varint,3,opt,name=exp" json:"exp,omitempty"`
	Money            *int32       `protobuf:"varint,4,opt,name=money" json:"money,omitempty"`
	FriendPoint      *int32       `protobuf:"varint,5,opt,name=friendPoint" json:"friendPoint,omitempty"`
	StaminaNow       *int32       `protobuf:"varint,6,opt,name=staminaNow" json:"staminaNow,omitempty"`
	StaminaMax       *int32       `protobuf:"varint,7,opt,name=staminaMax" json:"staminaMax,omitempty"`
	StaminaRecover   *uint32      `protobuf:"varint,8,opt,name=staminaRecover" json:"staminaRecover,omitempty"`
	GotMoney         *int32       `protobuf:"varint,9,opt,name=gotMoney" json:"gotMoney,omitempty"`
	GotExp           *int32       `protobuf:"varint,10,opt,name=gotExp" json:"gotExp,omitempty"`
	GotChip          *int32       `protobuf:"varint,11,opt,name=gotChip" json:"gotChip,omitempty"`
	GotFriendPoint   *int32       `protobuf:"varint,12,opt,name=gotFriendPoint" json:"gotFriendPoint,omitempty"`
	GotUnit          []*UserUnit  `protobuf:"bytes,13,rep,name=gotUnit" json:"gotUnit,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *RspClearQuest) Reset()         { *m = RspClearQuest{} }
func (m *RspClearQuest) String() string { return proto.CompactTextString(m) }
func (*RspClearQuest) ProtoMessage()    {}

func (m *RspClearQuest) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *RspClearQuest) GetRank() int32 {
	if m != nil && m.Rank != nil {
		return *m.Rank
	}
	return 0
}

func (m *RspClearQuest) GetExp() int32 {
	if m != nil && m.Exp != nil {
		return *m.Exp
	}
	return 0
}

func (m *RspClearQuest) GetMoney() int32 {
	if m != nil && m.Money != nil {
		return *m.Money
	}
	return 0
}

func (m *RspClearQuest) GetFriendPoint() int32 {
	if m != nil && m.FriendPoint != nil {
		return *m.FriendPoint
	}
	return 0
}

func (m *RspClearQuest) GetStaminaNow() int32 {
	if m != nil && m.StaminaNow != nil {
		return *m.StaminaNow
	}
	return 0
}

func (m *RspClearQuest) GetStaminaMax() int32 {
	if m != nil && m.StaminaMax != nil {
		return *m.StaminaMax
	}
	return 0
}

func (m *RspClearQuest) GetStaminaRecover() uint32 {
	if m != nil && m.StaminaRecover != nil {
		return *m.StaminaRecover
	}
	return 0
}

func (m *RspClearQuest) GetGotMoney() int32 {
	if m != nil && m.GotMoney != nil {
		return *m.GotMoney
	}
	return 0
}

func (m *RspClearQuest) GetGotExp() int32 {
	if m != nil && m.GotExp != nil {
		return *m.GotExp
	}
	return 0
}

func (m *RspClearQuest) GetGotChip() int32 {
	if m != nil && m.GotChip != nil {
		return *m.GotChip
	}
	return 0
}

func (m *RspClearQuest) GetGotFriendPoint() int32 {
	if m != nil && m.GotFriendPoint != nil {
		return *m.GotFriendPoint
	}
	return 0
}

func (m *RspClearQuest) GetGotUnit() []*UserUnit {
	if m != nil {
		return m.GotUnit
	}
	return nil
}

type ReqGetQuestInfo struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ReqGetQuestInfo) Reset()         { *m = ReqGetQuestInfo{} }
func (m *ReqGetQuestInfo) String() string { return proto.CompactTextString(m) }
func (*ReqGetQuestInfo) ProtoMessage()    {}

func (m *ReqGetQuestInfo) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type RspGetQuestInfo struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	QuestId          *uint32      `protobuf:"varint,2,opt,name=questId" json:"questId,omitempty"`
	CurrentStatus    *uint32      `protobuf:"varint,3,opt,name=currentStatus" json:"currentStatus,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *RspGetQuestInfo) Reset()         { *m = RspGetQuestInfo{} }
func (m *RspGetQuestInfo) String() string { return proto.CompactTextString(m) }
func (*RspGetQuestInfo) ProtoMessage()    {}

func (m *RspGetQuestInfo) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *RspGetQuestInfo) GetQuestId() uint32 {
	if m != nil && m.QuestId != nil {
		return *m.QuestId
	}
	return 0
}

func (m *RspGetQuestInfo) GetCurrentStatus() uint32 {
	if m != nil && m.CurrentStatus != nil {
		return *m.CurrentStatus
	}
	return 0
}

// =========== Trap ====================================================================//
type TrapInjuredValue struct {
	TrapIndex        *int32   `protobuf:"varint,1,opt,name=trapIndex" json:"trapIndex,omitempty"`
	TrapLevel        *int32   `protobuf:"varint,2,opt,name=trapLevel" json:"trapLevel,omitempty"`
	TrapValue        *float32 `protobuf:"fixed32,3,opt,name=trapValue" json:"trapValue,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *TrapInjuredValue) Reset()         { *m = TrapInjuredValue{} }
func (m *TrapInjuredValue) String() string { return proto.CompactTextString(m) }
func (*TrapInjuredValue) ProtoMessage()    {}

func (m *TrapInjuredValue) GetTrapIndex() int32 {
	if m != nil && m.TrapIndex != nil {
		return *m.TrapIndex
	}
	return 0
}

func (m *TrapInjuredValue) GetTrapLevel() int32 {
	if m != nil && m.TrapLevel != nil {
		return *m.TrapLevel
	}
	return 0
}

func (m *TrapInjuredValue) GetTrapValue() float32 {
	if m != nil && m.TrapValue != nil {
		return *m.TrapValue
	}
	return 0
}

type TrapInfo struct {
	TrapID           *uint32             `protobuf:"varint,1,req,name=trapID" json:"trapID,omitempty"`
	TrapType         *ETrapType          `protobuf:"varint,2,opt,name=trapType,enum=bbproto.ETrapType" json:"trapType,omitempty"`
	ValueIndex       *int32              `protobuf:"varint,3,opt,name=valueIndex" json:"valueIndex,omitempty"`
	InjuredInfo      []*TrapInjuredValue `protobuf:"bytes,4,rep,name=injuredInfo" json:"injuredInfo,omitempty"`
	EffectType       *int32              `protobuf:"varint,5,opt,name=effectType" json:"effectType,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *TrapInfo) Reset()         { *m = TrapInfo{} }
func (m *TrapInfo) String() string { return proto.CompactTextString(m) }
func (*TrapInfo) ProtoMessage()    {}

func (m *TrapInfo) GetTrapID() uint32 {
	if m != nil && m.TrapID != nil {
		return *m.TrapID
	}
	return 0
}

func (m *TrapInfo) GetTrapType() ETrapType {
	if m != nil && m.TrapType != nil {
		return *m.TrapType
	}
	return ETrapType_Move
}

func (m *TrapInfo) GetValueIndex() int32 {
	if m != nil && m.ValueIndex != nil {
		return *m.ValueIndex
	}
	return 0
}

func (m *TrapInfo) GetInjuredInfo() []*TrapInjuredValue {
	if m != nil {
		return m.InjuredInfo
	}
	return nil
}

func (m *TrapInfo) GetEffectType() int32 {
	if m != nil && m.EffectType != nil {
		return *m.EffectType
	}
	return 0
}

type UnitResource struct {
	Id               *uint32  `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Path             *string  `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Size             *int32   `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
	FileName         []string `protobuf:"bytes,4,rep,name=fileName" json:"fileName,omitempty"`
	Version          *int32   `protobuf:"varint,5,opt,name=version" json:"version,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *UnitResource) Reset()         { *m = UnitResource{} }
func (m *UnitResource) String() string { return proto.CompactTextString(m) }
func (*UnitResource) ProtoMessage()    {}

func (m *UnitResource) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *UnitResource) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *UnitResource) GetSize() int32 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *UnitResource) GetFileName() []string {
	if m != nil {
		return m.FileName
	}
	return nil
}

func (m *UnitResource) GetVersion() int32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

type UserUnit struct {
	UniqueId         *uint32 `protobuf:"varint,1,req,name=uniqueId" json:"uniqueId,omitempty"`
	UnitId           *uint32 `protobuf:"varint,2,opt,name=unitId" json:"unitId,omitempty"`
	Exp              *int32  `protobuf:"varint,3,opt,name=exp" json:"exp,omitempty"`
	Level            *int32  `protobuf:"varint,4,opt,name=level" json:"level,omitempty"`
	AddAttack        *int32  `protobuf:"varint,5,opt,name=addAttack" json:"addAttack,omitempty"`
	AddDefence       *int32  `protobuf:"varint,6,opt,name=addDefence" json:"addDefence,omitempty"`
	AddHp            *int32  `protobuf:"varint,7,opt,name=addHp" json:"addHp,omitempty"`
	LimitbreakLv     *int32  `protobuf:"varint,8,opt,name=limitbreakLv" json:"limitbreakLv,omitempty"`
	GetTime          *uint32 `protobuf:"varint,9,opt,name=getTime" json:"getTime,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UserUnit) Reset()         { *m = UserUnit{} }
func (m *UserUnit) String() string { return proto.CompactTextString(m) }
func (*UserUnit) ProtoMessage()    {}

func (m *UserUnit) GetUniqueId() uint32 {
	if m != nil && m.UniqueId != nil {
		return *m.UniqueId
	}
	return 0
}

func (m *UserUnit) GetUnitId() uint32 {
	if m != nil && m.UnitId != nil {
		return *m.UnitId
	}
	return 0
}

func (m *UserUnit) GetExp() int32 {
	if m != nil && m.Exp != nil {
		return *m.Exp
	}
	return 0
}

func (m *UserUnit) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *UserUnit) GetAddAttack() int32 {
	if m != nil && m.AddAttack != nil {
		return *m.AddAttack
	}
	return 0
}

func (m *UserUnit) GetAddDefence() int32 {
	if m != nil && m.AddDefence != nil {
		return *m.AddDefence
	}
	return 0
}

func (m *UserUnit) GetAddHp() int32 {
	if m != nil && m.AddHp != nil {
		return *m.AddHp
	}
	return 0
}

func (m *UserUnit) GetLimitbreakLv() int32 {
	if m != nil && m.LimitbreakLv != nil {
		return *m.LimitbreakLv
	}
	return 0
}

func (m *UserUnit) GetGetTime() uint32 {
	if m != nil && m.GetTime != nil {
		return *m.GetTime
	}
	return 0
}

type ReqGetUnitResource struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	UnitId           []uint32     `protobuf:"varint,2,rep,name=unitId" json:"unitId,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ReqGetUnitResource) Reset()         { *m = ReqGetUnitResource{} }
func (m *ReqGetUnitResource) String() string { return proto.CompactTextString(m) }
func (*ReqGetUnitResource) ProtoMessage()    {}

func (m *ReqGetUnitResource) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ReqGetUnitResource) GetUnitId() []uint32 {
	if m != nil {
		return m.UnitId
	}
	return nil
}

type RspGetUnitResource struct {
	Header           *ProtoHeader    `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Server           *string         `protobuf:"bytes,2,opt,name=server" json:"server,omitempty"`
	Unitres          []*UnitResource `protobuf:"bytes,3,rep,name=unitres" json:"unitres,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *RspGetUnitResource) Reset()         { *m = RspGetUnitResource{} }
func (m *RspGetUnitResource) String() string { return proto.CompactTextString(m) }
func (*RspGetUnitResource) ProtoMessage()    {}

func (m *RspGetUnitResource) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *RspGetUnitResource) GetServer() string {
	if m != nil && m.Server != nil {
		return *m.Server
	}
	return ""
}

func (m *RspGetUnitResource) GetUnitres() []*UnitResource {
	if m != nil {
		return m.Unitres
	}
	return nil
}

type ReqGetUserUnit struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	UnitId           []uint32     `protobuf:"varint,2,rep,name=unitId" json:"unitId,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ReqGetUserUnit) Reset()         { *m = ReqGetUserUnit{} }
func (m *ReqGetUserUnit) String() string { return proto.CompactTextString(m) }
func (*ReqGetUserUnit) ProtoMessage()    {}

func (m *ReqGetUserUnit) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ReqGetUserUnit) GetUnitId() []uint32 {
	if m != nil {
		return m.UnitId
	}
	return nil
}

type RspGetUserUnit struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Unit             []*UserUnit  `protobuf:"bytes,2,rep,name=unit" json:"unit,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *RspGetUserUnit) Reset()         { *m = RspGetUserUnit{} }
func (m *RspGetUserUnit) String() string { return proto.CompactTextString(m) }
func (*RspGetUserUnit) ProtoMessage()    {}

func (m *RspGetUserUnit) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *RspGetUserUnit) GetUnit() []*UserUnit {
	if m != nil {
		return m.Unit
	}
	return nil
}

type UserInfo struct {
	Uuid             *string   `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	UserId           *uint32   `protobuf:"varint,2,opt,name=userId" json:"userId,omitempty"`
	NickName         *string   `protobuf:"bytes,3,opt,name=nickName" json:"nickName,omitempty"`
	Rank             *int32    `protobuf:"varint,4,opt,name=rank" json:"rank,omitempty"`
	Exp              *int32    `protobuf:"varint,5,opt,name=exp" json:"exp,omitempty"`
	StaminaNow       *int32    `protobuf:"varint,6,opt,name=staminaNow" json:"staminaNow,omitempty"`
	StaminaMax       *int32    `protobuf:"varint,7,opt,name=staminaMax" json:"staminaMax,omitempty"`
	StaminaRecover   *uint32   `protobuf:"varint,8,opt,name=staminaRecover" json:"staminaRecover,omitempty"`
	Unit             *UserUnit `protobuf:"bytes,9,opt,name=unit" json:"unit,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}

func (m *UserInfo) GetUuid() string {
	if m != nil && m.Uuid != nil {
		return *m.Uuid
	}
	return ""
}

func (m *UserInfo) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *UserInfo) GetNickName() string {
	if m != nil && m.NickName != nil {
		return *m.NickName
	}
	return ""
}

func (m *UserInfo) GetRank() int32 {
	if m != nil && m.Rank != nil {
		return *m.Rank
	}
	return 0
}

func (m *UserInfo) GetExp() int32 {
	if m != nil && m.Exp != nil {
		return *m.Exp
	}
	return 0
}

func (m *UserInfo) GetStaminaNow() int32 {
	if m != nil && m.StaminaNow != nil {
		return *m.StaminaNow
	}
	return 0
}

func (m *UserInfo) GetStaminaMax() int32 {
	if m != nil && m.StaminaMax != nil {
		return *m.StaminaMax
	}
	return 0
}

func (m *UserInfo) GetStaminaRecover() uint32 {
	if m != nil && m.StaminaRecover != nil {
		return *m.StaminaRecover
	}
	return 0
}

func (m *UserInfo) GetUnit() *UserUnit {
	if m != nil {
		return m.Unit
	}
	return nil
}

type UserInfoDetail struct {
	User             *UserInfo    `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Account          *AccountInfo `protobuf:"bytes,2,opt,name=account" json:"account,omitempty"`
	Quest            *QuestLog    `protobuf:"bytes,3,opt,name=quest" json:"quest,omitempty"`
	UnitList         []*UserUnit  `protobuf:"bytes,4,rep,name=unitList" json:"unitList,omitempty"`
	Party            *PartyInfo   `protobuf:"bytes,5,opt,name=party" json:"party,omitempty"`
	Login            *LoginInfo   `protobuf:"bytes,6,opt,name=login" json:"login,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *UserInfoDetail) Reset()         { *m = UserInfoDetail{} }
func (m *UserInfoDetail) String() string { return proto.CompactTextString(m) }
func (*UserInfoDetail) ProtoMessage()    {}

func (m *UserInfoDetail) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UserInfoDetail) GetAccount() *AccountInfo {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *UserInfoDetail) GetQuest() *QuestLog {
	if m != nil {
		return m.Quest
	}
	return nil
}

func (m *UserInfoDetail) GetUnitList() []*UserUnit {
	if m != nil {
		return m.UnitList
	}
	return nil
}

func (m *UserInfoDetail) GetParty() *PartyInfo {
	if m != nil {
		return m.Party
	}
	return nil
}

func (m *UserInfoDetail) GetLogin() *LoginInfo {
	if m != nil {
		return m.Login
	}
	return nil
}

type AccountInfo struct {
	Review           *int32 `protobuf:"varint,1,opt,name=review" json:"review,omitempty"`
	PayTotal         *int32 `protobuf:"varint,2,opt,name=payTotal" json:"payTotal,omitempty"`
	PayMonth         *int32 `protobuf:"varint,3,opt,name=payMonth" json:"payMonth,omitempty"`
	Money            *int32 `protobuf:"varint,4,opt,name=money" json:"money,omitempty"`
	StonePay         *int32 `protobuf:"varint,5,opt,name=stonePay" json:"stonePay,omitempty"`
	StoneFree        *int32 `protobuf:"varint,6,opt,name=stoneFree" json:"stoneFree,omitempty"`
	Stone            *int32 `protobuf:"varint,7,opt,name=stone" json:"stone,omitempty"`
	FriendPoint      *int32 `protobuf:"varint,8,opt,name=friendPoint" json:"friendPoint,omitempty"`
	FirstSelectNum   *int32 `protobuf:"varint,9,opt,name=firstSelectNum" json:"firstSelectNum,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *AccountInfo) Reset()         { *m = AccountInfo{} }
func (m *AccountInfo) String() string { return proto.CompactTextString(m) }
func (*AccountInfo) ProtoMessage()    {}

func (m *AccountInfo) GetReview() int32 {
	if m != nil && m.Review != nil {
		return *m.Review
	}
	return 0
}

func (m *AccountInfo) GetPayTotal() int32 {
	if m != nil && m.PayTotal != nil {
		return *m.PayTotal
	}
	return 0
}

func (m *AccountInfo) GetPayMonth() int32 {
	if m != nil && m.PayMonth != nil {
		return *m.PayMonth
	}
	return 0
}

func (m *AccountInfo) GetMoney() int32 {
	if m != nil && m.Money != nil {
		return *m.Money
	}
	return 0
}

func (m *AccountInfo) GetStonePay() int32 {
	if m != nil && m.StonePay != nil {
		return *m.StonePay
	}
	return 0
}

func (m *AccountInfo) GetStoneFree() int32 {
	if m != nil && m.StoneFree != nil {
		return *m.StoneFree
	}
	return 0
}

func (m *AccountInfo) GetStone() int32 {
	if m != nil && m.Stone != nil {
		return *m.Stone
	}
	return 0
}

func (m *AccountInfo) GetFriendPoint() int32 {
	if m != nil && m.FriendPoint != nil {
		return *m.FriendPoint
	}
	return 0
}

func (m *AccountInfo) GetFirstSelectNum() int32 {
	if m != nil && m.FirstSelectNum != nil {
		return *m.FirstSelectNum
	}
	return 0
}

type PartyItem struct {
	UnitPos          *int32  `protobuf:"varint,1,opt,name=unitPos" json:"unitPos,omitempty"`
	UnitUniqueId     *uint32 `protobuf:"varint,2,opt,name=unitUniqueId" json:"unitUniqueId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PartyItem) Reset()         { *m = PartyItem{} }
func (m *PartyItem) String() string { return proto.CompactTextString(m) }
func (*PartyItem) ProtoMessage()    {}

func (m *PartyItem) GetUnitPos() int32 {
	if m != nil && m.UnitPos != nil {
		return *m.UnitPos
	}
	return 0
}

func (m *PartyItem) GetUnitUniqueId() uint32 {
	if m != nil && m.UnitUniqueId != nil {
		return *m.UnitUniqueId
	}
	return 0
}

type UnitParty struct {
	Id               *int32       `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Items            []*PartyItem `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *UnitParty) Reset()         { *m = UnitParty{} }
func (m *UnitParty) String() string { return proto.CompactTextString(m) }
func (*UnitParty) ProtoMessage()    {}

func (m *UnitParty) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *UnitParty) GetItems() []*PartyItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type PartyInfo struct {
	PartyList        []*UnitParty `protobuf:"bytes,1,rep,name=partyList" json:"partyList,omitempty"`
	CurrentParty     *int32       `protobuf:"varint,2,opt,name=currentParty" json:"currentParty,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *PartyInfo) Reset()         { *m = PartyInfo{} }
func (m *PartyInfo) String() string { return proto.CompactTextString(m) }
func (*PartyInfo) ProtoMessage()    {}

func (m *PartyInfo) GetPartyList() []*UnitParty {
	if m != nil {
		return m.PartyList
	}
	return nil
}

func (m *PartyInfo) GetCurrentParty() int32 {
	if m != nil && m.CurrentParty != nil {
		return *m.CurrentParty
	}
	return 0
}

type TerminalInfo struct {
	Channel          *string `protobuf:"bytes,1,opt,name=channel" json:"channel,omitempty"`
	DeviceName       *string `protobuf:"bytes,2,opt,name=deviceName" json:"deviceName,omitempty"`
	Uuid             *string `protobuf:"bytes,3,opt,name=uuid" json:"uuid,omitempty"`
	Os               *string `protobuf:"bytes,4,opt,name=os" json:"os,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TerminalInfo) Reset()         { *m = TerminalInfo{} }
func (m *TerminalInfo) String() string { return proto.CompactTextString(m) }
func (*TerminalInfo) ProtoMessage()    {}

func (m *TerminalInfo) GetChannel() string {
	if m != nil && m.Channel != nil {
		return *m.Channel
	}
	return ""
}

func (m *TerminalInfo) GetDeviceName() string {
	if m != nil && m.DeviceName != nil {
		return *m.DeviceName
	}
	return ""
}

func (m *TerminalInfo) GetUuid() string {
	if m != nil && m.Uuid != nil {
		return *m.Uuid
	}
	return ""
}

func (m *TerminalInfo) GetOs() string {
	if m != nil && m.Os != nil {
		return *m.Os
	}
	return ""
}

type LoginBonus struct {
	Type             *int32 `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Value            *int32 `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	BonusType        *int32 `protobuf:"varint,3,opt,name=bonusType" json:"bonusType,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *LoginBonus) Reset()         { *m = LoginBonus{} }
func (m *LoginBonus) String() string { return proto.CompactTextString(m) }
func (*LoginBonus) ProtoMessage()    {}

func (m *LoginBonus) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *LoginBonus) GetValue() int32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *LoginBonus) GetBonusType() int32 {
	if m != nil && m.BonusType != nil {
		return *m.BonusType
	}
	return 0
}

type LoginInfo struct {
	LoginTotal       *int32        `protobuf:"varint,1,opt,name=loginTotal" json:"loginTotal,omitempty"`
	LoginChain       *int32        `protobuf:"varint,2,opt,name=loginChain" json:"loginChain,omitempty"`
	LastLoginTime    *uint32       `protobuf:"varint,3,opt,name=lastLoginTime" json:"lastLoginTime,omitempty"`
	LastPlayTime     *uint32       `protobuf:"varint,4,opt,name=lastPlayTime" json:"lastPlayTime,omitempty"`
	FriendPointGet   *int32        `protobuf:"varint,5,opt,name=friendPointGet" json:"friendPointGet,omitempty"`
	FriendHelpCount  *int32        `protobuf:"varint,6,opt,name=friendHelpCount" json:"friendHelpCount,omitempty"`
	Bonus            []*LoginBonus `protobuf:"bytes,7,rep,name=bonus" json:"bonus,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *LoginInfo) Reset()         { *m = LoginInfo{} }
func (m *LoginInfo) String() string { return proto.CompactTextString(m) }
func (*LoginInfo) ProtoMessage()    {}

func (m *LoginInfo) GetLoginTotal() int32 {
	if m != nil && m.LoginTotal != nil {
		return *m.LoginTotal
	}
	return 0
}

func (m *LoginInfo) GetLoginChain() int32 {
	if m != nil && m.LoginChain != nil {
		return *m.LoginChain
	}
	return 0
}

func (m *LoginInfo) GetLastLoginTime() uint32 {
	if m != nil && m.LastLoginTime != nil {
		return *m.LastLoginTime
	}
	return 0
}

func (m *LoginInfo) GetLastPlayTime() uint32 {
	if m != nil && m.LastPlayTime != nil {
		return *m.LastPlayTime
	}
	return 0
}

func (m *LoginInfo) GetFriendPointGet() int32 {
	if m != nil && m.FriendPointGet != nil {
		return *m.FriendPointGet
	}
	return 0
}

func (m *LoginInfo) GetFriendHelpCount() int32 {
	if m != nil && m.FriendHelpCount != nil {
		return *m.FriendHelpCount
	}
	return 0
}

func (m *LoginInfo) GetBonus() []*LoginBonus {
	if m != nil {
		return m.Bonus
	}
	return nil
}

type PresentInfo struct {
	SerialId         *uint32 `protobuf:"varint,1,opt,name=serialId" json:"serialId,omitempty"`
	SendTime         *uint32 `protobuf:"varint,2,opt,name=sendTime" json:"sendTime,omitempty"`
	Type             *uint32 `protobuf:"varint,3,opt,name=type" json:"type,omitempty"`
	Value1           *uint32 `protobuf:"varint,4,opt,name=value1" json:"value1,omitempty"`
	Value2           *uint32 `protobuf:"varint,5,opt,name=value2" json:"value2,omitempty"`
	Message          *string `protobuf:"bytes,6,opt,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PresentInfo) Reset()         { *m = PresentInfo{} }
func (m *PresentInfo) String() string { return proto.CompactTextString(m) }
func (*PresentInfo) ProtoMessage()    {}

func (m *PresentInfo) GetSerialId() uint32 {
	if m != nil && m.SerialId != nil {
		return *m.SerialId
	}
	return 0
}

func (m *PresentInfo) GetSendTime() uint32 {
	if m != nil && m.SendTime != nil {
		return *m.SendTime
	}
	return 0
}

func (m *PresentInfo) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *PresentInfo) GetValue1() uint32 {
	if m != nil && m.Value1 != nil {
		return *m.Value1
	}
	return 0
}

func (m *PresentInfo) GetValue2() uint32 {
	if m != nil && m.Value2 != nil {
		return *m.Value2
	}
	return 0
}

func (m *PresentInfo) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

type SessionInfo struct {
	SessionId        *string `protobuf:"bytes,1,opt,name=sessionId" json:"sessionId,omitempty"`
	Uuid             *string `protobuf:"bytes,2,opt,name=uuid" json:"uuid,omitempty"`
	UserId           *uint32 `protobuf:"varint,3,opt,name=userId" json:"userId,omitempty"`
	QuestId          *uint32 `protobuf:"varint,4,opt,name=questId" json:"questId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SessionInfo) Reset()         { *m = SessionInfo{} }
func (m *SessionInfo) String() string { return proto.CompactTextString(m) }
func (*SessionInfo) ProtoMessage()    {}

func (m *SessionInfo) GetSessionId() string {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return ""
}

func (m *SessionInfo) GetUuid() string {
	if m != nil && m.Uuid != nil {
		return *m.Uuid
	}
	return ""
}

func (m *SessionInfo) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *SessionInfo) GetQuestId() uint32 {
	if m != nil && m.QuestId != nil {
		return *m.QuestId
	}
	return 0
}

type ReqGetUserInfo struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	UserId           *uint32      `protobuf:"varint,2,opt,name=userId" json:"userId,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ReqGetUserInfo) Reset()         { *m = ReqGetUserInfo{} }
func (m *ReqGetUserInfo) String() string { return proto.CompactTextString(m) }
func (*ReqGetUserInfo) ProtoMessage()    {}

func (m *ReqGetUserInfo) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ReqGetUserInfo) GetUserId() uint32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

type RspGetUserInfo struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	User             *UserInfo    `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *RspGetUserInfo) Reset()         { *m = RspGetUserInfo{} }
func (m *RspGetUserInfo) String() string { return proto.CompactTextString(m) }
func (*RspGetUserInfo) ProtoMessage()    {}

func (m *RspGetUserInfo) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *RspGetUserInfo) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

// -------------------------------------------------
type ReqAuthUser struct {
	Header           *ProtoHeader  `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Terminal         *TerminalInfo `protobuf:"bytes,2,opt,name=terminal" json:"terminal,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *ReqAuthUser) Reset()         { *m = ReqAuthUser{} }
func (m *ReqAuthUser) String() string { return proto.CompactTextString(m) }
func (*ReqAuthUser) ProtoMessage()    {}

func (m *ReqAuthUser) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ReqAuthUser) GetTerminal() *TerminalInfo {
	if m != nil {
		return m.Terminal
	}
	return nil
}

type RspAuthUser struct {
	Header           *ProtoHeader   `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	User             *UserInfo      `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	Account          *AccountInfo   `protobuf:"bytes,3,opt,name=account" json:"account,omitempty"`
	Quest            *QuestLog      `protobuf:"bytes,4,opt,name=quest" json:"quest,omitempty"`
	UnitList         []*UserUnit    `protobuf:"bytes,5,rep,name=unitList" json:"unitList,omitempty"`
	Party            *PartyInfo     `protobuf:"bytes,6,opt,name=party" json:"party,omitempty"`
	ServerTime       *uint32        `protobuf:"varint,7,opt,name=serverTime" json:"serverTime,omitempty"`
	Login            *LoginInfo     `protobuf:"bytes,8,opt,name=login" json:"login,omitempty"`
	Friends          *FriendList    `protobuf:"bytes,9,opt,name=friends" json:"friends,omitempty"`
	Present          []*PresentInfo `protobuf:"bytes,10,rep,name=present" json:"present,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *RspAuthUser) Reset()         { *m = RspAuthUser{} }
func (m *RspAuthUser) String() string { return proto.CompactTextString(m) }
func (*RspAuthUser) ProtoMessage()    {}

func (m *RspAuthUser) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *RspAuthUser) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *RspAuthUser) GetAccount() *AccountInfo {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *RspAuthUser) GetQuest() *QuestLog {
	if m != nil {
		return m.Quest
	}
	return nil
}

func (m *RspAuthUser) GetUnitList() []*UserUnit {
	if m != nil {
		return m.UnitList
	}
	return nil
}

func (m *RspAuthUser) GetParty() *PartyInfo {
	if m != nil {
		return m.Party
	}
	return nil
}

func (m *RspAuthUser) GetServerTime() uint32 {
	if m != nil && m.ServerTime != nil {
		return *m.ServerTime
	}
	return 0
}

func (m *RspAuthUser) GetLogin() *LoginInfo {
	if m != nil {
		return m.Login
	}
	return nil
}

func (m *RspAuthUser) GetFriends() *FriendList {
	if m != nil {
		return m.Friends
	}
	return nil
}

func (m *RspAuthUser) GetPresent() []*PresentInfo {
	if m != nil {
		return m.Present
	}
	return nil
}

// -------------------------------------------------
type ReqLoginPack struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	GetLogin         *bool        `protobuf:"varint,2,opt,name=getLogin" json:"getLogin,omitempty"`
	GetFriend        *bool        `protobuf:"varint,3,opt,name=getFriend" json:"getFriend,omitempty"`
	GetHelper        *bool        `protobuf:"varint,4,opt,name=getHelper" json:"getHelper,omitempty"`
	GetPresent       *bool        `protobuf:"varint,5,opt,name=getPresent" json:"getPresent,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ReqLoginPack) Reset()         { *m = ReqLoginPack{} }
func (m *ReqLoginPack) String() string { return proto.CompactTextString(m) }
func (*ReqLoginPack) ProtoMessage()    {}

func (m *ReqLoginPack) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ReqLoginPack) GetGetLogin() bool {
	if m != nil && m.GetLogin != nil {
		return *m.GetLogin
	}
	return false
}

func (m *ReqLoginPack) GetGetFriend() bool {
	if m != nil && m.GetFriend != nil {
		return *m.GetFriend
	}
	return false
}

func (m *ReqLoginPack) GetGetHelper() bool {
	if m != nil && m.GetHelper != nil {
		return *m.GetHelper
	}
	return false
}

func (m *ReqLoginPack) GetGetPresent() bool {
	if m != nil && m.GetPresent != nil {
		return *m.GetPresent
	}
	return false
}

type RspLoginPack struct {
	Header           *ProtoHeader   `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Login            *LoginInfo     `protobuf:"bytes,2,opt,name=login" json:"login,omitempty"`
	Friends          *FriendList    `protobuf:"bytes,3,opt,name=friends" json:"friends,omitempty"`
	Present          []*PresentInfo `protobuf:"bytes,4,rep,name=present" json:"present,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *RspLoginPack) Reset()         { *m = RspLoginPack{} }
func (m *RspLoginPack) String() string { return proto.CompactTextString(m) }
func (*RspLoginPack) ProtoMessage()    {}

func (m *RspLoginPack) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *RspLoginPack) GetLogin() *LoginInfo {
	if m != nil {
		return m.Login
	}
	return nil
}

func (m *RspLoginPack) GetFriends() *FriendList {
	if m != nil {
		return m.Friends
	}
	return nil
}

func (m *RspLoginPack) GetPresent() []*PresentInfo {
	if m != nil {
		return m.Present
	}
	return nil
}

type ReqRenameNick struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	NewNickName      *string      `protobuf:"bytes,2,opt,name=newNickName" json:"newNickName,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ReqRenameNick) Reset()         { *m = ReqRenameNick{} }
func (m *ReqRenameNick) String() string { return proto.CompactTextString(m) }
func (*ReqRenameNick) ProtoMessage()    {}

func (m *ReqRenameNick) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ReqRenameNick) GetNewNickName() string {
	if m != nil && m.NewNickName != nil {
		return *m.NewNickName
	}
	return ""
}

type RspRenameNick struct {
	Header           *ProtoHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	NewNickName      *string      `protobuf:"bytes,2,opt,name=newNickName" json:"newNickName,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *RspRenameNick) Reset()         { *m = RspRenameNick{} }
func (m *RspRenameNick) String() string { return proto.CompactTextString(m) }
func (*RspRenameNick) ProtoMessage()    {}

func (m *RspRenameNick) GetHeader() *ProtoHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *RspRenameNick) GetNewNickName() string {
	if m != nil && m.NewNickName != nil {
		return *m.NewNickName
	}
	return ""
}

func init() {
	proto.RegisterEnum("bbproto.EUnitType", EUnitType_name, EUnitType_value)
	proto.RegisterEnum("bbproto.EUnitRace", EUnitRace_name, EUnitRace_value)
	proto.RegisterEnum("bbproto.EFriendState", EFriendState_name, EFriendState_value)
	proto.RegisterEnum("bbproto.EQuestState", EQuestState_name, EQuestState_value)
	proto.RegisterEnum("bbproto.ETrapType", ETrapType_name, ETrapType_value)
	proto.RegisterEnum("bbproto.EQuestGridType", EQuestGridType_name, EQuestGridType_value)
	proto.RegisterEnum("bbproto.EGridStar", EGridStar_name, EGridStar_value)
	proto.RegisterEnum("bbproto.QuestBoostType", QuestBoostType_name, QuestBoostType_value)
}
