// Code generated by protoc-gen-go.
// source: person.proto
// DO NOT EDIT!

package bbproto

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type PersonPhoneType int32

const (
	Person_mobile PersonPhoneType = 0
	Person_home   PersonPhoneType = 1
	Person_work   PersonPhoneType = 2
)

var PersonPhoneType_name = map[int32]string{
	0: "mobile",
	1: "home",
	2: "work",
}
var PersonPhoneType_value = map[string]int32{
	"mobile": 0,
	"home":   1,
	"work":   2,
}

func (x PersonPhoneType) Enum() *PersonPhoneType {
	p := new(PersonPhoneType)
	*p = x
	return p
}
func (x PersonPhoneType) String() string {
	return proto.EnumName(PersonPhoneType_name, int32(x))
}
func (x *PersonPhoneType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PersonPhoneType_value, data, "PersonPhoneType")
	if err != nil {
		return err
	}
	*x = PersonPhoneType(value)
	return nil
}

type Person struct {
	Name             *string              `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Id               *int32               `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Email            *string              `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Phone            []*PersonPhoneNumber `protobuf:"bytes,4,rep,name=phone" json:"phone,omitempty"`
	TestPacked       []int32              `protobuf:"varint,5,rep,packed,name=test_packed" json:"test_packed,omitempty"`
	TestDeprecated   *int32               `protobuf:"varint,6,opt,name=test_deprecated" json:"test_deprecated,omitempty"`
	Foreach          *int32               `protobuf:"varint,7,opt,name=foreach" json:"foreach,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}

func (m *Person) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Person) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Person) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

func (m *Person) GetPhone() []*PersonPhoneNumber {
	if m != nil {
		return m.Phone
	}
	return nil
}

func (m *Person) GetTestPacked() []int32 {
	if m != nil {
		return m.TestPacked
	}
	return nil
}

func (m *Person) GetTestDeprecated() int32 {
	if m != nil && m.TestDeprecated != nil {
		return *m.TestDeprecated
	}
	return 0
}

func (m *Person) GetForeach() int32 {
	if m != nil && m.Foreach != nil {
		return *m.Foreach
	}
	return 0
}

type PersonPhoneNumber struct {
	Number           *string          `protobuf:"bytes,1,req,name=number" json:"number,omitempty"`
	Type             *PersonPhoneType `protobuf:"varint,2,opt,name=type,enum=bbproto.PersonPhoneType,def=1" json:"type,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *PersonPhoneNumber) Reset()         { *m = PersonPhoneNumber{} }
func (m *PersonPhoneNumber) String() string { return proto.CompactTextString(m) }
func (*PersonPhoneNumber) ProtoMessage()    {}

const Default_PersonPhoneNumber_Type PersonPhoneType = Person_home

func (m *PersonPhoneNumber) GetNumber() string {
	if m != nil && m.Number != nil {
		return *m.Number
	}
	return ""
}

func (m *PersonPhoneNumber) GetType() PersonPhoneType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Default_PersonPhoneNumber_Type
}

type OpaqueMessageList struct {
	MessagesList     [][]byte `protobuf:"bytes,1,rep,name=messages_list" json:"messages_list,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *OpaqueMessageList) Reset()         { *m = OpaqueMessageList{} }
func (m *OpaqueMessageList) String() string { return proto.CompactTextString(m) }
func (*OpaqueMessageList) ProtoMessage()    {}

func (m *OpaqueMessageList) GetMessagesList() [][]byte {
	if m != nil {
		return m.MessagesList
	}
	return nil
}

func init() {
	proto.RegisterEnum("bbproto.PersonPhoneType", PersonPhoneType_name, PersonPhoneType_value)
}
