// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using bbproto;

public class GachaModule : ModuleBase {

    protected string titleText = "";

	public GachaModule(UIConfigItem config):base(  config) {
		CreateUI<GachaView> ();
	}

    public override void InitUI () {
        base.InitUI ();
    }
    
    public override void ShowUI () {
        base.ShowUI ();
        BeforeSetTitleView();
        SetTitleView();
    }
    
    public override void HideUI () {
        base.HideUI ();
    }
    
    public override void DestoryUI () {
        base.DestoryUI ();
    }

    protected virtual void BeforeSetTitleView(){

    }

    private void SetTitleView(){
//        CallBackDispatcherArgs cbdArgs = new CallBackDispatcherArgs("SetTitleView", titleText);
		view.CallbackView("SetTitleView", titleText);
    }

}