// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using bbproto;

public class GachaModule : ModuleBase {

    protected string titleText = "";

	public GachaModule(UIConfigItem config,params object[] args):base(config, args) {
		CreateUI<GachaView> ();
	}
    
    public override void ShowUI () {
        base.ShowUI ();
//        SetTitleView();
//		foreach (var item in moduleData.Keys) {
//			Debug.Log ("gacha: " + item);
//		}
		
		if (moduleData != null) {
			(view as GachaView).Enter(moduleData);
		}
    }

}