// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using bbproto;

public class RareGachaModule: GachaModule{

	public RareGachaModule(UIConfigItem config):base(  config) {
//		CreateUI<RareGachaWindowLogic
	}

    protected override void BeforeSetTitleView(){
        titleText = TextCenter.GetText("RareScratch");
    }
}