// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using bbproto;


public class DelFriend: ProtoManager {
    // req && rsp
    private bbproto.ReqDelFriend reqDelFriend;
    private bbproto.RspDelFriend rspDelFriend;
    // state for req
    private uint friendUid;
    // data
    private TFriendList friendList;
    
    public DelFriend() {
    }
    
    ~DelFriend () {
    }
    
    public static void SendRequest(ResponseCallback callBack, uint friendUid) {
        DelFriend delFriend = new DelFriend();
        delFriend.friendUid = friendUid;
//        delFriend.OnRequest(null, callBack);
    }
    
    //Property: request server parameters
    public uint FriendUid { get { return friendUid; } set { friendUid = value; } }
    
    
    //make request packet==>TODO rename to request
    public override bool MakePacket() {
        Proto = Protocol.DEL_FRIEND;
        reqType = typeof(ReqDelFriend);
        rspType = typeof(RspDelFriend);
        
        reqDelFriend = new ReqDelFriend();
        reqDelFriend.header = new ProtoHeader();
        reqDelFriend.header.apiVer = Protocol.API_VERSION;
        reqDelFriend.header.userId = DataCenter.Instance.UserInfo.UserId;
        
        //request params
        reqDelFriend.friendUid = friendUid;
        
        ErrorMsg err = SerializeData(reqDelFriend); // save to Data for send out
        
        return (err.Code == (int)ErrorCode.SUCCESS);
    }
    
}

