// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.IO;
using ProtoBuf;

namespace Utility
{

	public class ProtobufSerializer
	{

		public static byte[] SerializeToBytes<T> (T instance){
			using (MemoryStream ms = new MemoryStream ())
			{
				byte[] output = null;
				if (instance == null){
					return null;
				}
				Serializer.Serialize<T>(ms, instance);
				return Converter.StreamToBytes(ms);
			}
		}

		public static T ParseFormString<T> (String source){
			MemoryStream ms = Converter.StringToStream(source);
			return Serializer.Deserialize<T>(ms);
		}
	}
}

