package cs

//error code
const (
	SUCCESS          = 0
	FAILED           = -1
	INVALID_PARAMS   = -2
	MARSHAL_ERROR    = -3
	UNMARSHAL_ERROR  = -4
	IOREAD_ERROR     = -5
	IOWRITE_ERROR    = -6
	CONNECT_DB_ERROR = -7
	SET_DB_ERROR     = -8
)

//user
const (
	EU_USER_BASE          = -100
	EU_INVALID_USERID     = EU_USER_BASE - 1
	EU_GET_USERINFO_FAIL  = EU_USER_BASE - 2
	EU_USER_NOT_EXISTS    = EU_USER_BASE - 3
	EU_GET_NEWUSERID_FAIL = EU_USER_BASE - 4
)

//friend
const (
	EF_FRIEND_BASE         = -200
	EF_FRIEND_NOT_EXISTS   = EF_FRIEND_BASE - 1
	EF_GET_FRIENDINFO_FAIL = EF_FRIEND_BASE - 2
	EF_ADD_FRIEND_FAIL     = EF_FRIEND_BASE - 3
	EF_DEL_FRIEND_FAIL     = EF_FRIEND_BASE - 4
	EF_ACCEPT_FRIEND_FAIL  = EF_FRIEND_BASE - 5
)
