// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

public class DBManager
{
    private static DBManager instance;
    private const string DB_SECRET = "#%WDssdferG*";

    public static DBManager Instance
    {
        get
        {
            if(instance  == null)
                instance = new DBManager();
            
            return instance;
        }
    }

    public DBManager(){

    }

    public void Init(){

    }

}

